# Generated by Django 4.2.16 on 2026-01-06 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TarefaInteligencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('status', models.CharField(choices=[('a_fazer', 'A Fazer'), ('em_progresso', 'Em Progresso'), ('validacao', 'Aguardando Validação'), ('concluido', 'Concluído')], default='a_fazer', max_length=20, verbose_name='Status')),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_conclusao', models.DateField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('prioridade', models.BooleanField(default=False, verbose_name='Prioridade Alta')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Tarefa de Inteligência',
                'verbose_name_plural': 'Tarefas de Inteligência',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
