# Generated by Django 4.2.16 on 2026-01-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_inteligencia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefainteligencia',
            name='data_limite',
            field=models.DateField(blank=True, null=True, verbose_name='Prazo'),
        ),
    ]
