# Generated by Django 4.2.16 on 2026-01-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_inteligencia', '0002_tarefainteligencia_data_limite'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefainteligencia',
            name='cor',
            field=models.CharField(choices=[('azul', 'Azul'), ('verde', 'Verde'), ('amarelo', 'Amarelo'), ('laranja', 'Laranja'), ('vermelho', 'Vermelho'), ('roxo', 'Roxo'), ('rosa', 'Rosa'), ('cinza', 'Cinza')], default='azul', max_length=20, verbose_name='Cor'),
        ),
    ]
