# Generated by Django 4.2.16 on 2026-01-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_inteligencia', '0003_tarefainteligencia_cor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefainteligencia',
            name='cor',
            field=models.CharField(choices=[('azul', 'Azul'), ('verde', 'Verde'), ('amarelo', 'Amarelo'), ('laranja', 'Laranja'), ('vermelho', 'Vermelho')], default='azul', max_length=20, verbose_name='Cor'),
        ),
        migrations.AlterField(
            model_name='tarefainteligencia',
            name='responsavel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Responsável'),
        ),
    ]
