# Generated by Django 4.2.16 on 2026-01-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_inteligencia', '0004_alter_tarefainteligencia_cor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefainteligencia',
            name='prioridade',
            field=models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], default='media', max_length=20, verbose_name='Prioridade'),
        ),
    ]
