# Generated by Django 4.2.16 on 2026-01-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_inteligencia', '0005_alter_tarefainteligencia_prioridade'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefainteligencia',
            name='responsavel_cor',
            field=models.CharField(default='#6c757d', max_length=7, verbose_name='Cor do Responsável'),
        ),
    ]
