# Generated by Django 4.2.16 on 2026-01-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_inteligencia', '0006_tarefainteligencia_responsavel_cor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefainteligencia',
            name='responsavel_cor',
            field=models.CharField(default='azul', max_length=20, verbose_name='Cor do Responsável'),
        ),
    ]
