# Generated by Django 6.0 on 2026-01-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_inteligencia', '0007_alter_tarefainteligencia_responsavel_cor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefainteligencia',
            name='destinado',
            field=models.CharField(choices=[('desenvolvimento', 'Desenvolvimento'), ('inteligencia', 'Inteligência')], default='inteligencia', max_length=25, verbose_name='Destinado'),
        ),
    ]
