# Generated by Django 6.0 on 2026-01-13 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_inteligencia', '0008_tarefainteligencia_destinado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefainteligencia',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/kanban/'),
        ),
    ]
