# Generated by Django 4.2.16 on 2026-01-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_inteligencia', '0009_tarefainteligencia_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefainteligencia',
            name='prioridade',
            field=models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('avaliar', 'Avaliar')], default='media', max_length=20, verbose_name='Prioridade'),
        ),
        migrations.AlterField(
            model_name='tarefainteligencia',
            name='responsavel_cor',
            field=models.CharField(blank=True, default='azul', max_length=20, null=True, verbose_name='Cor do Responsável'),
        ),
    ]
