# Generated by Django 6.0.1 on 2026-01-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_inteligencia', '0011_tarefainteligencia_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefainteligencia',
            name='prioridade',
            field=models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('avaliar', 'Avaliar')], default='avaliar', max_length=20, verbose_name='Prioridade'),
        ),
    ]
