# Generated by Django 6.0.1 on 2026-01-16 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_inteligencia', '0013_alter_tarefainteligencia_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarefainteligencia',
            options={'ordering': ['-data_criacao', '-id'], 'verbose_name': 'Tarefa de Inteligência', 'verbose_name_plural': 'Tarefas de Inteligência'},
        ),
    ]
