# Generated by Django 6.0.1 on 2026-01-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_inteligencia', '0014_alter_tarefainteligencia_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefainteligencia',
            name='status',
            field=models.CharField(choices=[('avaliar', 'Avaliar'), ('a_fazer', 'A Fazer'), ('em_progresso', 'Em Progresso'), ('validacao', 'Aguardando Validação'), ('concluido', 'Concluído')], default='avaliar', max_length=20, verbose_name='Status'),
        ),
    ]
