# Generated by Django 6.0.1 on 2026-01-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_inteligencia', '0015_alter_tarefainteligencia_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefainteligencia',
            name='responsavel',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Responsável'),
        ),
    ]
