# Generated by Django 6.0.1 on 2026-01-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_inteligencia', '0016_alter_tarefainteligencia_responsavel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefainteligencia',
            name='responsavel',
            field=models.CharField(blank=True, choices=[('analia', 'Anália'), ('eurico', 'Eurico'), ('fernanda', 'Fernanda'), ('gabriel', 'Gabriel'), ('joao', 'João'), ('julio', 'Julio'), ('murillo', 'Murillo')], max_length=50, null=True, verbose_name='Responsável'),
        ),
    ]
