# Generated by Django 6.0.6 on 2026-06-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_inteligencia', '0017_alter_tarefainteligencia_responsavel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefainteligencia',
            name='responsavel',
            field=models.CharField(blank=True, choices=[('analia', 'Anália'), ('eurico', 'Eurico'), ('fernanda', 'Fernanda'), ('gabriel', 'Gabriel'), ('joao', 'João'), ('julio', 'Julio'), ('murillo', 'Murillo'), ('kethleen', 'Kethleen'), ('nathalia', 'Nathalia')], max_length=50, null=True, verbose_name='Responsável'),
        ),
    ]
