# Generated by Django 6.0.6 on 2026-06-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_inteligencia', '0018_alter_tarefainteligencia_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefainteligencia',
            name='enviado_kanban_ti',
            field=models.BooleanField(default=False, verbose_name='Enviado ao Kanban TI'),
        ),
        migrations.AlterField(
            model_name='tarefainteligencia',
            name='destinado',
            field=models.CharField(choices=[('desenvolvimento', 'Desenvolvimento'), ('inteligencia', 'Inteligência'), ('TI', 'T.I')], default='inteligencia', max_length=25, verbose_name='Destinado'),
        ),
    ]
