# Generated by Django 6.0.6 on 2026-06-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_inteligencia', '0019_tarefainteligencia_enviado_kanban_ti_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefainteligencia',
            name='mensagem_status',
            field=models.TextField(blank=True, default='Ticket criado, retornaremos em até 48h.', verbose_name='Mensagem de status'),
        ),
        migrations.AddField(
            model_name='tarefainteligencia',
            name='prazo_resposta',
            field=models.CharField(blank=True, default='48h', max_length=100, verbose_name='Prazo de resposta'),
        ),
    ]
