# Generated by Django 6.0.6 on 2026-06-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_inteligencia', '0020_tarefainteligencia_mensagem_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefainteligencia',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em'),
        ),
    ]
