# Generated by Django 6.0.6 on 2026-06-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_inteligencia', '0021_tarefainteligencia_criado_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefainteligencia',
            name='motivo_recusa',
            field=models.TextField(blank=True, default='', verbose_name='Motivo da recusa'),
        ),
        migrations.AlterField(
            model_name='tarefainteligencia',
            name='status',
            field=models.CharField(choices=[('avaliar', 'Avaliar'), ('a_fazer', 'A Fazer'), ('em_progresso', 'Em Progresso'), ('validacao', 'Aguardando Validação'), ('concluido', 'Concluído'), ('recusado', 'Recusado')], default='avaliar', max_length=20, verbose_name='Status'),
        ),
    ]
