# Generated by Django 6.0.1 on 2026-06-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_acionamentos', '0002_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('cnh', models.CharField(blank=True, max_length=20, verbose_name='CNH')),
                ('chave_pix', models.CharField(blank=True, max_length=140, verbose_name='Chave PIX')),
                ('banco', models.CharField(blank=True, max_length=80, verbose_name='Banco')),
                ('tipo_conta', models.CharField(blank=True, choices=[('CORRENTE', 'Corrente'), ('POUPANCA', 'Poupança')], max_length=10, verbose_name='Tipo de conta')),
                ('agencia', models.CharField(blank=True, max_length=10, verbose_name='Agência')),
                ('conta', models.CharField(blank=True, max_length=20, verbose_name='Conta')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('clientes_vinculados', models.ManyToManyField(blank=True, related_name='agentes_vinculados', to='controle_acionamentos.cliente', verbose_name='Clientes vinculados')),
            ],
            options={
                'verbose_name': 'Agente',
                'verbose_name_plural': 'Agentes',
                'ordering': ['-criado_em'],
            },
        ),
    ]
