# Generated by Django 6.0.1 on 2026-06-22 12:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_acionamentos', '0003_agente'),
    ]

    operations = [
        migrations.CreateModel(
            name='FranquiaAgente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('valor_acionamento', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valor do acionamento')),
                ('franquia_km', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Franquia de KM')),
                ('franquia_horas', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Franquia de horas')),
                ('valor_km_excedente', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valor por KM excedente')),
                ('valor_hora_excedente', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valor por hora excedente')),
                ('escalonamento_automatico', models.BooleanField(default=False, verbose_name='Escalonamento automático')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='franquias', to='controle_acionamentos.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Franquia de Agente',
                'verbose_name_plural': 'Franquias de Agente',
                'ordering': ['-criado_em'],
                'constraints': [models.UniqueConstraint(fields=('cliente', 'nome'), name='unique_franquia_cliente_nome')],
            },
        ),
    ]
