# Generated by Django 6.0.1 on 2026-06-25 14:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_acionamentos', '0004_franquiaagente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='franquiaagente',
            name='franquia_km',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Franquia de KM'),
        ),
    ]
