# Generated by Django 6.0.1 on 2026-06-26 20:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_acionamentos', '0005_alter_franquiaagente_franquia_km'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_servico', models.CharField(max_length=120, verbose_name='Nome do serviço')),
                ('valor_acionamento', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valor do acionamento')),
                ('franquia_km', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Franquia de KM')),
                ('franquia_horas', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Franquia de horas')),
                ('valor_km_excedente', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valor por KM excedente')),
                ('valor_hora_excedente', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valor por hora excedente')),
                ('origem', models.CharField(max_length=200, verbose_name='Origem')),
                ('destino', models.CharField(blank=True, max_length=200, verbose_name='Destino')),
                ('placa_agente', models.CharField(blank=True, max_length=8, verbose_name='Placa do agente')),
                ('motorista', models.CharField(blank=True, max_length=120, verbose_name='Motorista')),
                ('placa_motorista', models.CharField(blank=True, max_length=8, verbose_name='Placa do motorista')),
                ('numero_motorista', models.CharField(blank=True, max_length=20, verbose_name='Número do motorista')),
                ('data_hora_solicitado', models.DateTimeField(db_index=True, verbose_name='Data/hora solicitado')),
                ('data_hora_inicio', models.DateTimeField(verbose_name='Data/hora de início')),
                ('data_hora_final', models.DateTimeField(verbose_name='Data/hora final')),
                ('km_inicio', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='KM inicial')),
                ('km_final', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='KM final')),
                ('pedagio', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Pedágio')),
                ('km_total', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='KM total')),
                ('horas_total', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=6, null=True, verbose_name='Horas totais')),
                ('km_excedente', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='KM excedente')),
                ('hora_excedente', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=6, null=True, verbose_name='Hora excedente')),
                ('valor_agente', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Valor do agente')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acionamentos', to='controle_acionamentos.agente', verbose_name='Agente')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acionamentos', to='controle_acionamentos.cliente', verbose_name='Cliente')),
                ('franquia_agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acionamentos', to='controle_acionamentos.franquiaagente', verbose_name='Franquia de agente')),
                ('responsavel_agente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acionamentos', to='controle_acionamentos.responsavelagente', verbose_name='Responsável de agente')),
            ],
            options={
                'verbose_name': 'Acionamento',
                'verbose_name_plural': 'Acionamentos',
                'ordering': ['-data_hora_solicitado'],
            },
        ),
    ]
