# Generated by Django 6.0.1 on 2026-07-03 12:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_acionamentos', '0006_acionamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acionamento',
            name='franquia_km',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Franquia de KM'),
        ),
    ]
