# Generated by Django 6.0.1 on 2026-07-14 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_acionamentos', '0007_alter_acionamento_franquia_km'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcionamentoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(max_length=100, verbose_name='Campo')),
                ('valor_anterior', models.TextField(blank=True, verbose_name='Valor anterior')),
                ('valor_novo', models.TextField(blank=True, verbose_name='Valor novo')),
                ('editado_em', models.DateTimeField(auto_now_add=True, verbose_name='Editado em')),
                ('acionamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico', to='controle_acionamentos.acionamento', verbose_name='Acionamento')),
                ('editado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Editado por')),
            ],
            options={
                'verbose_name': 'Histórico de edição',
                'verbose_name_plural': 'Históricos de edição',
                'ordering': ['-editado_em'],
            },
        ),
    ]
