# Generated by Django 6.0.1 on 2026-07-15 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_acionamentos', '0008_acionamentohistorico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='acionamento',
            name='criado_por',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acionamentos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
    ]
