# Generated by Django 6.0.1 on 2026-07-16 17:58

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_acionamentos', '0009_acionamento_criado_por'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('MOTO_1_AGENTE', 'Moto | 1 agente moto monitoramento ativo'), ('CARRO_1_AGENTE', 'Carro | 1 agente carro monitoramento ativo'), ('CARRO_2_AGENTES', 'Carro | 2 agentes carro monitoramento ativo'), ('CARRO_1_AGENTE_1P', 'Carro | 1 agente carro monitoramento ativo 1P+'), ('CARRO_2_AGENTES_2P', 'Carro | 2 agentes carro monitoramento ativo 2P+')], max_length=20, verbose_name='Serviço')),
                ('ativo', models.BooleanField(default=False, verbose_name='Ativo')),
                ('valor_acionamento', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valor do acionamento')),
                ('franquia_km', models.PositiveIntegerField(verbose_name='Franquia de KM')),
                ('franquia_horas', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Franquia de horas')),
                ('valor_km_excedente', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valor por KM excedente')),
                ('valor_hora_excedente', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valor por hora excedente')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicos', to='controle_acionamentos.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Serviço de Cliente',
                'verbose_name_plural': 'Serviços de Cliente',
                'ordering': ['-criado_em'],
                'constraints': [models.UniqueConstraint(fields=('cliente', 'nome'), name='unique_servico_cliente_nome')],
            },
        ),
    ]
