# Generated by Django 6.0.1 on 2026-07-16 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_acionamentos', '0010_servicocliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='acionamento',
            name='servico_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acionamentos', to='controle_acionamentos.servicocliente', verbose_name='Serviço do cliente'),
        ),
    ]
