# Generated by Django 6.0.1 on 2026-07-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_acionamentos', '0011_acionamento_servico_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='acionamento',
            name='valor_cliente',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Valor do cliente'),
        ),
    ]
