# Generated by Django 6.0.1 on 2026-07-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_acionamentos', '0012_acionamento_valor_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='CNPJ'),
        ),
    ]
