# Generated by Django 6.0.1 on 2026-05-13 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaTarefaAdministrativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cor', models.CharField(default='#665b1d', max_length=20, verbose_name='Cor (hex)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Categoria de Tarefa',
                'verbose_name_plural': 'Categorias de Tarefas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='BlocoSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('nao_esquecer', 'Importantes / Não Esquecer'), ('diario', 'Diário'), ('observacao', 'Outros / Observação')], max_length=20, verbose_name='Tipo do Bloco')),
                ('semana_iso', models.PositiveIntegerField(verbose_name='Semana ISO')),
                ('ano', models.PositiveIntegerField(verbose_name='Ano')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Bloco Semanal',
                'verbose_name_plural': 'Blocos Semanais',
                'unique_together': {('tipo', 'semana_iso', 'ano')},
            },
        ),
        migrations.CreateModel(
            name='FuncionarioAdministrativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('perfil', models.CharField(choices=[('gestor', 'Gestor'), ('operador', 'Operador')], default='operador', max_length=20, verbose_name='Perfil')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='funcionario_administrativo', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Funcionário Administrativo',
                'verbose_name_plural': 'Funcionários Administrativos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ItemBlocoSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('is_fixo', models.BooleanField(default=False, help_text='Itens fixos são copiados automaticamente para a semana seguinte', verbose_name='Item fixo')),
                ('is_done', models.BooleanField(default=False, verbose_name='Concluído')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('bloco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='controle_administrativo.blocosemanal', verbose_name='Bloco')),
            ],
            options={
                'verbose_name': 'Item do Bloco',
                'verbose_name_plural': 'Itens do Bloco',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='TarefaModeloAdministrativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('dia_da_semana', models.CharField(choices=[('segunda', 'Segunda-feira'), ('terca', 'Terça-feira'), ('quarta', 'Quarta-feira'), ('quinta', 'Quinta-feira'), ('sexta', 'Sexta-feira')], max_length=10, verbose_name='Dia da Semana')),
                ('periodo', models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde')], max_length=10, verbose_name='Período')),
                ('tipo_controle', models.CharField(choices=[('checkbox', 'Checkbox'), ('percentual', 'Percentual')], default='checkbox', max_length=15, verbose_name='Tipo de Controle')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de exibição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_modelo', to='controle_administrativo.categoriatarefaadministrativa', verbose_name='Categoria')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarefas_modelo', to='controle_administrativo.funcionarioadministrativo', verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Tarefa Modelo',
                'verbose_name_plural': 'Tarefas Modelo',
                'ordering': ['dia_da_semana', 'periodo', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='ExecucaoTarefaAdministrativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana_iso', models.PositiveIntegerField(verbose_name='Semana ISO')),
                ('ano', models.PositiveIntegerField(verbose_name='Ano')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('atrasada', 'Atrasada'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='pendente', max_length=15, verbose_name='Status')),
                ('is_done', models.BooleanField(default=False, verbose_name='Concluída')),
                ('comentario', models.TextField(blank=True, verbose_name='Comentário')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execucoes_atualizadas', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('tarefa_modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='execucoes', to='controle_administrativo.tarefamodeloadministrativa', verbose_name='Tarefa Modelo')),
            ],
            options={
                'verbose_name': 'Execução de Tarefa',
                'verbose_name_plural': 'Execuções de Tarefas',
                'ordering': ['tarefa_modelo__dia_da_semana', 'tarefa_modelo__periodo'],
                'unique_together': {('tarefa_modelo', 'semana_iso', 'ano')},
            },
        ),
    ]
