# Generated by Django 5.0.1 on 2026-05-14 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_administrativo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='execucaotarefaadministrativa',
            name='comentario',
        ),
        migrations.AddField(
            model_name='execucaotarefaadministrativa',
            name='concluido_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Concluído em'),
        ),
        migrations.AddField(
            model_name='execucaotarefaadministrativa',
            name='concluido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execucoes_concluidas', to=settings.AUTH_USER_MODEL, verbose_name='Concluído por'),
        ),
        migrations.AddField(
            model_name='execucaotarefaadministrativa',
            name='prazo',
            field=models.DateField(blank=True, null=True, verbose_name='Prazo'),
        ),
        migrations.AddField(
            model_name='tarefamodeloadministrativa',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.CreateModel(
            name='ComentarioTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField(verbose_name='Comentário')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('is_done', models.BooleanField(default=False, verbose_name='Visto')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios_tarefas', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('execucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='controle_administrativo.execucaotarefaadministrativa', verbose_name='Execução')),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
                'ordering': ['criado_em'],
            },
        ),
    ]
