# Generated by Django 5.0.1 on 2026-05-15 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_administrativo', '0002_remove_execucaotarefaadministrativa_comentario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='execucaotarefaadministrativa',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='execucaotarefaadministrativa',
            name='descricao_avulsa',
            field=models.TextField(blank=True, verbose_name='Descrição (avulso)'),
        ),
        migrations.AddField(
            model_name='execucaotarefaadministrativa',
            name='dia_avulso',
            field=models.CharField(blank=True, choices=[('segunda', 'Segunda-feira'), ('terca', 'Terça-feira'), ('quarta', 'Quarta-feira'), ('quinta', 'Quinta-feira'), ('sexta', 'Sexta-feira')], max_length=10, verbose_name='Dia (avulso)'),
        ),
        migrations.AddField(
            model_name='execucaotarefaadministrativa',
            name='is_avulsa',
            field=models.BooleanField(default=False, verbose_name='Tarefa avulsa'),
        ),
        migrations.AddField(
            model_name='execucaotarefaadministrativa',
            name='periodo_avulso',
            field=models.CharField(blank=True, choices=[('manha', 'Manhã'), ('tarde', 'Tarde')], max_length=10, verbose_name='Período (avulso)'),
        ),
        migrations.AddField(
            model_name='execucaotarefaadministrativa',
            name='responsavel_avulso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execucoes_avulsas', to='controle_administrativo.funcionarioadministrativo', verbose_name='Responsável (avulso)'),
        ),
        migrations.AddField(
            model_name='execucaotarefaadministrativa',
            name='titulo_avulso',
            field=models.CharField(blank=True, max_length=200, verbose_name='Título (avulso)'),
        ),
        migrations.AlterField(
            model_name='execucaotarefaadministrativa',
            name='tarefa_modelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='execucoes', to='controle_administrativo.tarefamodeloadministrativa', verbose_name='Tarefa Modelo'),
        ),
        migrations.CreateModel(
            name='LeituraComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lido_em', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras', to='controle_administrativo.comentariotarefa', verbose_name='Comentário')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras_comentarios', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Leitura de Comentário',
                'verbose_name_plural': 'Leituras de Comentários',
                'unique_together': {('comentario', 'usuario')},
            },
        ),
    ]
