# Generated by Django 5.0.1 on 2026-05-19 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_administrativo', '0004_itemblocosemanal_criado_em_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarefaDivisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana_iso', models.PositiveIntegerField(verbose_name='Semana ISO')),
                ('ano', models.PositiveIntegerField(verbose_name='Ano')),
                ('conteudo', models.CharField(max_length=300, verbose_name='Tarefa')),
                ('is_done', models.BooleanField(default=False, verbose_name='Concluída')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas_divisao', to='controle_administrativo.funcionarioadministrativo', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Tarefa da Divisão',
                'verbose_name_plural': 'Tarefas da Divisão',
                'ordering': ['ordem', 'criado_em'],
            },
        ),
    ]
