# Generated by Django 5.0.1 on 2026-05-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_administrativo', '0005_tarefadivisao'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefadivisao',
            name='is_fixo',
            field=models.BooleanField(default=False, verbose_name='Item fixo'),
        ),
        migrations.AddField(
            model_name='tarefadivisao',
            name='prazo',
            field=models.DateField(blank=True, null=True, verbose_name='Prazo'),
        ),
        migrations.AlterField(
            model_name='blocosemanal',
            name='tipo',
            field=models.CharField(choices=[('nao_esquecer', 'Não Esquecer'), ('quinzenal', 'Quinzenal'), ('mensal', 'Mensal')], max_length=20, verbose_name='Tipo do Bloco'),
        ),
    ]
