# Generated by Django 5.0.1 on 2026-05-21 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_administrativo', '0006_tarefadivisao_is_fixo_tarefadivisao_prazo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefadivisao',
            name='tipo',
            field=models.CharField(choices=[('hoje', 'Tarefas de Hoje'), ('semana', 'Tarefas da Semana'), ('mensal', 'Tarefas Mensais')], default='semana', max_length=10, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='ComentarioTarefaDivisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField(verbose_name='Comentário')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios_divisao', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='controle_administrativo.tarefadivisao', verbose_name='Tarefa')),
            ],
            options={
                'verbose_name': 'Comentário de Tarefa da Divisão',
                'verbose_name_plural': 'Comentários de Tarefas da Divisão',
                'ordering': ['criado_em'],
            },
        ),
    ]
