# Generated by Django 5.0.1 on 2026-05-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_administrativo', '0007_tarefadivisao_tipo_comentariotarefadivisao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execucaotarefaadministrativa',
            name='prazo',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Prazo'),
        ),
    ]
