# Generated by Django 5.0.1 on 2026-05-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_administrativo', '0008_alter_execucaotarefaadministrativa_prazo'),
    ]

    operations = [
        migrations.AddField(
            model_name='execucaotarefaadministrativa',
            name='oculta',
            field=models.BooleanField(default=False, help_text='Quando True, esta execução é ignorada no painel (soft delete). Usado quando uma tarefa recorrente é desativada.', verbose_name='Oculta'),
        ),
    ]
