# Generated by Django 5.0.1 on 2026-05-26 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_administrativo', '0009_execucaotarefaadministrativa_oculta'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefadivisao',
            name='oculta',
            field=models.BooleanField(default=False, help_text='Quando True, esta tarefa é ignorada no painel (soft delete). Usado ao excluir tarefas fixas para evitar recriação automática.', verbose_name='Oculta'),
        ),
    ]
