# Generated by Django 5.0.1 on 2026-06-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_administrativo', '0010_tarefadivisao_oculta'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemblocosemanal',
            name='oculta',
            field=models.BooleanField(default=False, help_text='Soft-delete: item escondido do painel, não apagado fisicamente', verbose_name='Oculto'),
        ),
    ]
