# Generated by Django 6.0.6 on 2026-07-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_administrativo', '0011_itemblocosemanal_oculta'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionarioadministrativo',
            name='senha_alterada_em',
            field=models.DateTimeField(blank=True, help_text='Registra a conclusão da troca de senha inicial (primeiro acesso).', null=True, verbose_name='Senha alterada em'),
        ),
        migrations.AddField(
            model_name='funcionarioadministrativo',
            name='senha_provisoria',
            field=models.BooleanField(default=False, help_text='Quando True, o funcionário é obrigado a trocar a senha no próximo acesso antes de usar o painel. Marcado ao criar/redefinir com senha padrão temporária.', verbose_name='Senha provisória'),
        ),
    ]
