# Generated by Django 5.1.3 on 2025-11-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requisicao", "0057_requisicoes_iccid"),
    ]

    operations = [
        migrations.AddField(
            model_name="antenista_card",
            name="lucro",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="antenista_card",
            name="valor_cliente",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="antenista_card",
            name="valor_isca",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="antenista_card",
            name="valor_prestador",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="antenista_card",
            name="valor_total",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
    ]
