# Generated by Django 5.1.3 on 2025-11-12 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requisicao", "0058_antenista_card_lucro_antenista_card_valor_cliente_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Antenista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=120, unique=True)),
                ("estado", models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        # NOTE: AlterField operations were intentionally removed from this migration.
        # The workflow will be:
        # 1) Create model Antenista (this migration)
        # 2) Run data migration to populate Antenista and set references (0059)
        # 3) Generate and apply a separate migration that alters the 'nome' fields to ForeignKey
        #    (makemigrations will create that after data migration has run).
    ]
