# Generated by Django 5.1.3 on 2025-11-12 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requisicao", "0059_migrate_estoque_and_card_to_antenista"),
    ]

    operations = [
        migrations.AddField(
            model_name="antenista_card",
            name="nome_texto",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="estoque_antenista",
            name="nome_texto",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="antenista_card",
            name="nome",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cards",
                to="requisicao.antenista",
            ),
        ),
        migrations.AlterField(
            model_name="estoque_antenista",
            name="nome",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="estoques",
                to="requisicao.antenista",
            ),
        ),
    ]
