# Generated by Django 5.0.1 on 2025-12-01 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0060_antenista_card_nome_texto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicoes',
            name='cor_card',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='requisicoes',
            name='kanban_status',
            field=models.CharField(blank=True, choices=[('a_fazer', 'A Fazer'), ('em_progresso', 'Em Progresso'), ('auditoria', 'Auditoria')], default='a_fazer', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='requisicoes',
            name='prioridade',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='KanbanHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(blank=True, max_length=20, null=True)),
                ('status_novo', models.CharField(max_length=20)),
                ('data_movimentacao', models.DateTimeField(auto_now_add=True)),
                ('requisicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_kanban', to='requisicao.requisicoes')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_kanban', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico Kanban',
                'verbose_name_plural': 'Históricos Kanban',
                'ordering': ['-data_movimentacao'],
            },
        ),
    ]
