# Generated by Django 5.0.1 on 2025-12-01 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0061_requisicoes_cor_card_requisicoes_kanban_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicoes',
            name='quantidade_expedida',
            field=models.IntegerField(default=0, help_text='Quantidade já expedida desta requisição'),
        ),
        migrations.AddField(
            model_name='requisicoes',
            name='requisicao_original_id',
            field=models.ForeignKey(blank=True, help_text='Requisição original de onde esta foi derivada (expedição parcial)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes_parciais', to='requisicao.requisicoes'),
        ),
        migrations.CreateModel(
            name='KanbanAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('movimento', 'Movimento de Card'), ('expedicao_parcial', 'Expedição Parcial'), ('expedicao_total', 'Expedição Total')], max_length=20)),
                ('coluna_origem', models.CharField(blank=True, max_length=20, null=True)),
                ('coluna_destino', models.CharField(blank=True, max_length=20, null=True)),
                ('quantidade_expedida', models.IntegerField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data_acao', models.DateTimeField(auto_now_add=True)),
                ('requisicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_auditoria', to='requisicao.requisicoes')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes_kanban', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Auditoria Kanban',
                'verbose_name_plural': 'Logs de Auditoria Kanban',
                'ordering': ['-data_acao'],
            },
        ),
    ]
