# Generated by Django 5.0.1 on 2025-12-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0062_requisicoes_quantidade_expedida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicoes',
            name='responsavel_manutencao',
            field=models.CharField(blank=True, choices=[('GuilhermeAmarante', 'Guilherme Amarante'), ('Talita.Espinosa', 'Talita Espinosa'), ('Vinicius.Rodrigues', 'Vinicius Rodrigues'), ('PATRICIALORENA', 'Patricia Lorena')], help_text='Responsável pela manutenção/configuração do equipamento', max_length=50, null=True),
        ),
    ]
