# Generated by Django 5.0.1 on 2025-12-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0063_requisicoes_responsavel_manutencao'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicoes',
            name='ids_auditados',
            field=models.TextField(blank=True, default='', help_text='IDs dos equipamentos que passaram pela auditoria antes da expedição', max_length=180000, null=True),
        ),
        migrations.AddField(
            model_name='requisicoes',
            name='verificacao_plataforma',
            field=models.BooleanField(default=False, help_text='Indica se houve verificação via plataforma durante a auditoria'),
        ),
    ]
