# Generated by Django 5.0.1 on 2025-12-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0064_requisicoes_ids_auditados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicoes',
            name='customizacao_conforme',
            field=models.BooleanField(default=False, help_text='Indica se a customização está de acordo com o solicitado'),
        ),
    ]
