# Generated by Django 6.0 on 2026-01-06 15:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('requisicao', '0065_requisicoes_customizacao_conforme'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # NOTE: a criação de AuditLog/CampoAlterado e seus índices vive em
        # 0066_auditlog_campoalterado_and_more (ramo irmão, unido por 0074_merge).
        # As operações de CreateModel/AddIndex idênticas que existiam aqui foram
        # removidas porque, num banco construído do zero, os dois 0066 rodam e a
        # tabela/índices colidiam ("table requisicao_auditlog already exists").
        # Resta apenas o AlterField, que é exclusivo desta migration.
        migrations.AlterField(
            model_name='requisicoes',
            name='responsavel_manutencao',
            field=models.CharField(blank=True, choices=[('GuilhermeAmarante', 'Guilherme Amarante'), ('Talita.Espinosa', 'Talita Espinosa'), ('Vinicius.Rodrigues', 'Vinicius Rodrigues'), ('Patricia.Costa', 'Patricia Costa'), ('Anália', 'Anália Venancio'), ('Evellyn.Taila', 'Evellyn Taila'), ('Tiago.Faria', 'Tiago Faria'), ('Inteligencia', 'Inteligencia')], help_text='Responsável pela manutenção/configuração do equipamento', max_length=50, null=True),
        ),
    ]
