# Generated by Django 6.0 on 2026-01-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0066_alter_requisicoes_responsavel_manutencao_auditlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcompanhamentoEx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_campo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='registrodeacompanhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(max_length=50)),
                ('cliente', models.CharField(max_length=100)),
                ('origem', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('agente', models.CharField(max_length=100)),
                ('placa_agente', models.CharField(max_length=10)),
                ('motorista', models.CharField(max_length=100)),
                ('placa_motorista', models.CharField(max_length=10)),
                ('data_solicitada', models.DateField()),
                ('horario_solicitado', models.TimeField()),
                ('data_inicial', models.DateField()),
                ('horario_inicio', models.TimeField()),
                ('data_final', models.DateField()),
                ('horario_finalizacao', models.TimeField()),
                ('km_inicio', models.IntegerField()),
                ('km_final', models.IntegerField()),
                ('km_total', models.IntegerField()),
                ('ocorrencia', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Registro de Acompanhamento',
                'verbose_name_plural': 'Registros de Acompanhamento',
                'ordering': ['-criado_em'],
            },
        ),
    ]
