# Generated by Django 6.0 on 2026-01-07 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0067_acompanhamentoex_registrodeacompanhamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListAcompanhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(db_index=True, max_length=100)),
                ('cliente', models.CharField(db_index=True, max_length=150)),
                ('origem', models.CharField(max_length=150)),
                ('destino', models.CharField(max_length=150)),
                ('data_inicial', models.DateField()),
                ('data_final', models.DateField()),
                ('km_total', models.PositiveIntegerField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Acompanhamento',
                'verbose_name_plural': 'Acompanhamentos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.DeleteModel(
            name='AcompanhamentoEx',
        ),
        migrations.AlterField(
            model_name='registrodeacompanhamento',
            name='agente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registrodeacompanhamento',
            name='cliente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registrodeacompanhamento',
            name='data_final',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrodeacompanhamento',
            name='data_inicial',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrodeacompanhamento',
            name='data_solicitada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrodeacompanhamento',
            name='destino',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registrodeacompanhamento',
            name='horario_finalizacao',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrodeacompanhamento',
            name='horario_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrodeacompanhamento',
            name='horario_solicitado',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrodeacompanhamento',
            name='km_final',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrodeacompanhamento',
            name='km_inicio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrodeacompanhamento',
            name='km_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrodeacompanhamento',
            name='motorista',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registrodeacompanhamento',
            name='origem',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registrodeacompanhamento',
            name='placa_agente',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='registrodeacompanhamento',
            name='placa_motorista',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='registrodeacompanhamento',
            name='protocolo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='listacompanhamento',
            name='registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listagens', to='requisicao.registrodeacompanhamento'),
        ),
    ]
