# Generated by Django 6.0 on 2026-01-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0068_listacompanhamento_delete_acompanhamentoex_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrodeacompanhamento',
            options={'ordering': ['-criado_em']},
        ),
        migrations.RemoveField(
            model_name='registrodeacompanhamento',
            name='protocolo',
        ),
        migrations.AlterField(
            model_name='registrodeacompanhamento',
            name='agente',
            field=models.CharField(default='NÃO INFORMADO', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registrodeacompanhamento',
            name='cliente',
            field=models.CharField(default='NÃO INFORMADO', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registrodeacompanhamento',
            name='data_final',
            field=models.DateField(null=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registrodeacompanhamento',
            name='data_inicial',
            field=models.DateField(null=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registrodeacompanhamento',
            name='data_solicitada',
            field=models.DateField(null=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registrodeacompanhamento',
            name='destino',
            field=models.CharField(default='NÃO INFORMADO', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registrodeacompanhamento',
            name='horario_finalizacao',
            field=models.TimeField(null=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registrodeacompanhamento',
            name='horario_inicio',
            field=models.TimeField(null=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registrodeacompanhamento',
            name='horario_solicitado',
            field=models.TimeField(null=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registrodeacompanhamento',
            name='km_final',
            field=models.IntegerField(null=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registrodeacompanhamento',
            name='km_inicio',
            field=models.IntegerField(null=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registrodeacompanhamento',
            name='km_total',
            field=models.IntegerField(null=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registrodeacompanhamento',
            name='motorista',
            field=models.CharField(default='NÃO INFORMADO', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registrodeacompanhamento',
            name='origem',
            field=models.CharField(default='NÃO INFORMADO', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registrodeacompanhamento',
            name='placa_agente',
            field=models.CharField(default='NÃO INFORMADO', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registrodeacompanhamento',
            name='placa_motorista',
            field=models.CharField(default='NÃO INFORMADO', max_length=10),
            preserve_default=False,
        ),
    ]
