# Generated by Django 6.0 on 2026-01-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0069_alter_registrodeacompanhamento_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrodeacompanhamento',
            name='nome_user',
            field=models.CharField(db_index=True, default='NAO INFORMADO', max_length=150),
            preserve_default=False,
        ),
    ]
