# Generated by Django 6.0 on 2026-01-08 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0070_registrodeacompanhamento_nome_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listacompanhamento',
            name='protocolo',
        ),
        migrations.RemoveField(
            model_name='registrodeacompanhamento',
            name='nome_user',
        ),
    ]
