# Generated by Django 6.0 on 2026-01-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0071_remove_listacompanhamento_protocolo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrodeacompanhamento',
            name='nome_user',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
