# Generated by Django 6.0 on 2026-01-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0072_registrodeacompanhamento_nome_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrodeacompanhamento',
            name='data_final',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='registrodeacompanhamento',
            name='data_inicial',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='registrodeacompanhamento',
            name='data_solicitada',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='registrodeacompanhamento',
            name='horario_finalizacao',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='registrodeacompanhamento',
            name='horario_inicio',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='registrodeacompanhamento',
            name='horario_solicitado',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='registrodeacompanhamento',
            name='km_final',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='registrodeacompanhamento',
            name='km_inicio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='registrodeacompanhamento',
            name='km_total',
            field=models.IntegerField(),
        ),
    ]
