# Generated by Django 6.0 on 2026-01-09 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0073_alter_registrodeacompanhamento_data_final_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrodeacompanhamento',
            options={'ordering': ['-criado_em'], 'permissions': [('view_listacompanhamento', 'Pode visualizar lista de acompanhamentos')]},
        ),
    ]
