# Generated by Django 5.1.2 on 2026-01-08 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0066_auditlog_campoalterado_and_more'),
        ('requisicao', '0073_alter_registrodeacompanhamento_data_final_and_more'),
    ]

    operations = [
    ]
