# Generated by Django 6.0 on 2026-01-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0074_alter_registrodeacompanhamento_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrodeacompanhamento',
            name='agente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registrodeacompanhamento',
            name='cliente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registrodeacompanhamento',
            name='data_final',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrodeacompanhamento',
            name='data_inicial',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrodeacompanhamento',
            name='data_solicitada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrodeacompanhamento',
            name='destino',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registrodeacompanhamento',
            name='horario_finalizacao',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrodeacompanhamento',
            name='horario_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrodeacompanhamento',
            name='horario_solicitado',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrodeacompanhamento',
            name='km_final',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrodeacompanhamento',
            name='km_inicio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrodeacompanhamento',
            name='km_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrodeacompanhamento',
            name='motorista',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registrodeacompanhamento',
            name='origem',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registrodeacompanhamento',
            name='placa_agente',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='registrodeacompanhamento',
            name='placa_motorista',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
