# Generated by Django 5.1.2 on 2026-01-09 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0074_alter_registrodeacompanhamento_options'),
        ('requisicao', '0074_merge_20260108_1712'),
    ]

    operations = [
    ]
