# Generated by Django 6.0 on 2026-01-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0075_alter_registrodeacompanhamento_agente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrodeacompanhamento',
            name='horario_total',
            field=models.TimeField(blank=True, help_text='Tempo total do acompanhamento', null=True),
        ),
        migrations.AddField(
            model_name='registrodeacompanhamento',
            name='responsavel_agente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
