# Generated by Django 6.0 on 2026-01-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0076_registrodeacompanhamento_horario_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrodeacompanhamento',
            name='horario_total',
            field=models.DurationField(blank=True, help_text='Tempo total do acompanhamento', null=True),
        ),
    ]
