# Generated by Django 5.1.2 on 2026-01-12 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0075_merge_20260109_1702'),
        ('requisicao', '0077_alter_registrodeacompanhamento_horario_total'),
    ]

    operations = [
    ]
