# Generated by Django 6.0 on 2026-01-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0078_merge_20260112_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrodeacompanhamento',
            name='pedagio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Valor do Pedágio (R$)'),
        ),
        migrations.AddField(
            model_name='registrodeacompanhamento',
            name='valor_agente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Valor do Agente (R$)'),
        ),
    ]
