# Generated by Django 6.0 on 2026-01-16 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franquia', '0002_remove_registrodefranquia_km_excedente'),
        ('requisicao', '0079_registrodeacompanhamento_pedagio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrodeacompanhamento',
            name='franquia',
            field=models.ForeignKey(blank=True, help_text='Franquia contratada para este acompanhamento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acompanhamentos', to='franquia.registrodefranquia'),
        ),
        migrations.AddField(
            model_name='registrodeacompanhamento',
            name='horario_excedente',
            field=models.DurationField(blank=True, help_text='Tempo excedente em relação à franquia', null=True),
        ),
        migrations.AddField(
            model_name='registrodeacompanhamento',
            name='km_excedente',
            field=models.IntegerField(blank=True, help_text='KM excedente em relação à franquia', null=True),
        ),
        migrations.AlterField(
            model_name='registrodeacompanhamento',
            name='km_total',
            field=models.IntegerField(blank=True, help_text='KM total rodado', null=True),
        ),
    ]
