# Generated by Django 6.0 on 2026-01-22 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0080_registrodeacompanhamento_franquia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrodeacompanhamento',
            name='franquia',
        ),
        migrations.DeleteModel(
            name='ListAcompanhamento',
        ),
        migrations.DeleteModel(
            name='registrodeacompanhamento',
        ),
    ]
