# Generated by Django 6.0 on 2026-01-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0081_remove_registrodeacompanhamento_franquia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicoes',
            name='memoria_apagada',
            field=models.BooleanField(default=False, help_text='Indica se Apagaram a Memória do Equipamento'),
        ),
        migrations.AddField(
            model_name='requisicoes',
            name='verificacao_tp',
            field=models.BooleanField(default=False, help_text='Indica se houve verificação do TP conforme a Requisição'),
        ),
    ]
