# Generated by Django 6.0 on 2026-01-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0082_requisicoes_memoria_apagada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicoes',
            name='comercial',
            field=models.CharField(blank=True, choices=[('MAYRA', 'MAYRA'), ('DANIEL', 'DANIEL'), ('MARCIO', 'MARCIO'), ('CIDO', 'CIDO'), ('ALISON', 'ALISON'), ('THIAGO', 'THIAGO'), ('GOLDEN', 'GOLDEN'), ('ARMANDO', 'ARMANDO'), ('JOÃO', 'JOÃO'), ('INFINITY', 'INFINITY')], default='', max_length=100),
        ),
    ]
