# Generated by Django 6.0 on 2026-02-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0084_alter_requisicoes_motivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicoes',
            name='motivo',
            field=models.CharField(blank=True, choices=[('Tipo de Faturamento', 'Tipo de Faturamento'), ('Aquisicão Nova', 'Aquisicão Nova'), ('Manutenção', 'Manutenção'), ('Aditivo', 'Aditivo'), ('Acessórios', 'Acessórios'), ('Extravio', 'Extravio'), ('Teste', 'Teste'), ('Spot', 'Spot'), ('Isca Fast - Agente', 'Isca Fast - Agente'), ('Antenista', 'Antenista'), ('Reversa', 'Reversa'), ('Isca FAST', 'Isca FAST'), ('Substituição', 'Substituição'), ('Renovação', 'Renovação')], default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='requisicoes',
            name='observacoes',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
