# Generated by Django 6.0 on 2026-03-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0085_alter_requisicoes_motivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicoes',
            name='responsavel_manutencao',
            field=models.CharField(blank=True, choices=[('GuilhermeAmarante', 'Guilherme Amarante'), ('Talita.Espinosa', 'Talita Espinosa'), ('Vinicius.Rodrigues', 'Vinicius Rodrigues'), ('Patricia.Costa', 'Patricia Costa'), ('Anália', 'Anália Venancio'), ('Evellyn.Taila', 'Evellyn Taila'), ('kethleen.araujo', 'Kethleen Araujo'), ('Tiago.Faria', 'Tiago Faria'), ('Inteligencia', 'Inteligencia')], help_text='Responsável pela manutenção/configuração do equipamento', max_length=50, null=True),
        ),
    ]
