# Generated by Django 6.0 on 2026-04-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    # Compatibilidade com bancos que já aplicaram o histórico antigo
    # em 3 migrations separadas (0088/0089/0090).
    replaces = [
        ('requisicao', '0088_requisicoes_email'),
        ('requisicao', '0089_requisicoes_codigo_rastreio'),
        ('requisicao', '0090_requisicoes_tipo_entrega'),
    ]

    dependencies = [
        ('requisicao', '0087_alter_requisicoes_responsavel_manutencao'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicoes',
            name='codigo_rastreio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='requisicoes',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requisicoes',
            name='tipo_entrega',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
