# Generated by Django 6.0.6 on 2026-09-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0090_alter_requisicoes_tipo_customizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicoes',
            name='comercial',
            field=models.CharField(blank=True, choices=[('MAYRA', 'MAYRA'), ('DANIEL', 'DANIEL'), ('MARCIO', 'MARCIO'), ('CIDO', 'CIDO'), ('ALISON', 'ALISON'), ('THIAGO', 'THIAGO'), ('GOLDEN', 'GOLDEN'), ('ARMANDO', 'ARMANDO'), ('DANIELA', 'DANIELA'), ('INFINITY', 'INFINITY')], default='', max_length=100),
        ),
    ]
