# Generated by Django 6.0 on 2026-10-02 11:44

import django.db.models.deletion
from django.db import migrations, models


def _quantidade(valor):
    """numero_de_equipamentos é texto livre: só dígitos viram quantidade (o
    resto vira 0, o mesmo critério do `_quantidade` da API de IDs)."""
    valor = (valor or "").strip()
    return int(valor) if valor.isdigit() else 0


def _backfill_itens(apps, schema_editor):
    """Cada requisição existente vira 1 item com os valores que ela já tinha
    (até aqui a requisição só aceitava um tipo de produto)."""
    Requisicoes = apps.get_model('requisicao', 'Requisicoes')
    ItemRequisicao = apps.get_model('requisicao', 'ItemRequisicao')

    ja_migradas = set(ItemRequisicao.objects.values_list('requisicao_id', flat=True))
    campos = ('id', 'tipo_produto_id', 'numero_de_equipamentos', 'tipo_customizacao',
              'valor_unitario')
    itens = [
        ItemRequisicao(
            requisicao_id=rid,
            tipo_produto_id=produto_id,
            quantidade=_quantidade(numero),
            customizacao=customizacao or '',
            valor_unitario=valor or 0,
        )
        for rid, produto_id, numero, customizacao, valor
        in Requisicoes.objects.values_list(*campos).iterator()
        if rid not in ja_migradas  # idempotente
    ]
    ItemRequisicao.objects.bulk_create(itens, batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
        ('requisicao', '0091_alter_requisicoes_comercial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemRequisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('customizacao', models.CharField(blank=True, choices=[('Sem custumização', 'Sem custumização'), ('Caixa de papelão', 'Caixa de papelão'), ('Caixa de papelão (bateria desacoplada)', 'Caixa de papelão (bateria desacoplada)'), ('Caixa de papelão + DF', 'Caixa de papelão + DF'), ('Termo branco', 'Termo branco'), ('Termo branco + imã', 'Termo branco + imã'), ('Termo branco + D.F ', 'Termo branco + D.F'), ('Termo branco slim ', 'Termo branco slim'), ('Termo branco slim + D.F +EQT  ', 'Termo branco slim + D.F +EQT'), ('Termo cinza slim + D.F +EQT  ', 'Termo cinza slim + D.F +EQT'), ('Termo branco  (isopor) ', 'Termo branco  (isopor)'), ('Termo branco - bateria externa ', 'Termo branco - bateria externa'), ('Termo marrom + imã', 'Termo marrom + imã'), ('Termo cinza', 'Termo cinza'), ('Termo cinza + imã', 'Termo cinza + imã'), ('Termo preto', 'Termo preto'), ('Termo preto + imã', 'Termo preto + imã'), ('Termo vermelho', 'Termo vermelho'), ('Termo vermelho + imã', 'Termo vermelho + imã'), ('Termo branco - slim', 'Termo branco - slim'), ('Termo marrom slim +D.F + EQT', 'Termo marrom slim +D.F + EQT'), ('Termo marrom', 'Termo marrom'), ('Termo marrom + ETQ', 'Termo marrom + ETQ'), ('Termo marrom slim', 'Termo marrom slim'), ('Caixa blindada', 'Caixa blindada'), ('Tênis/ Sapato', 'Tênis/ Sapato'), ('Projetor', 'Projetor'), ('Caixa de som', 'Caixa de som'), ('Luminaria', 'Luminaria'), ('Alexa', 'Alexa'), ('Video Game', 'Video Game'), ('Secador de cabelo', 'Secador de cabelo'), ('Roteador', 'Roteador'), ('Relogio digital', 'Relogio digital')], default='', max_length=50)),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('numeros_referencia', models.TextField(blank=True, default='')),
                ('requisicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='requisicao.requisicoes')),
                ('tipo_produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_requisicao', to='produto.produto')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RunPython(_backfill_itens, migrations.RunPython.noop),
    ]
