# Generated by Django 6.0.1 on 2026-10-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisicao', '0092_item_requisicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicoes',
            name='responsavel_manutencao',
            field=models.CharField(blank=True, choices=[('GuilhermeAmarante', 'Guilherme Amarante'), ('Talita.Espinosa', 'Talita Espinosa'), ('Vinicius.Rodrigues', 'Vinicius Rodrigues'), ('Patricia.Costa', 'Patricia Costa'), ('Anália', 'Anália Venancio'), ('Evellyn.Taila', 'Evellyn Taila'), ('kethleen.araujo', 'Kethleen Araujo'), ('Tiago.Faria', 'Tiago Faria'), ('Inteligencia', 'Inteligencia'), ('RafaelaPereira', 'Rafaela Pereira'), ('Shirley', 'Shirley Ribeiro')], help_text='Responsável pela manutenção/configuração do equipamento', max_length=50, null=True),
        ),
    ]
