# Generated by Django 6.0 on 2026-01-14 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('franquia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrodefranquia',
            name='km_excedente',
        ),
    ]
