# Generated by Django 6.0 on 2026-07-08 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(editable=False, max_length=11, unique=True, verbose_name='Protocolo')),
                ('cliente', models.CharField(max_length=160, verbose_name='Cliente')),
                ('categoria', models.CharField(choices=[('HARDWARE', 'Hardware'), ('CONECTIVIDADE', 'Conectividade'), ('CHIP_SIM', 'Chip / SIM'), ('SOFTWARE', 'Software'), ('INSTALACAO', 'Instalação'), ('OUTROS', 'Outros')], max_length=20, verbose_name='Categoria')),
                ('numero_equipamento', models.CharField(max_length=60, verbose_name='Nº do equipamento')),
                ('problema_relatado', models.TextField(verbose_name='Problema relatado')),
                ('procedimento_realizado', models.TextField(blank=True, null=True, verbose_name='Procedimento realizado')),
                ('tratativa', models.TextField(blank=True, null=True, verbose_name='Tratativa')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ANALISE', 'Em análise'), ('ENCAMINHADO', 'Encaminhado'), ('BLOQUEADO', 'Bloqueado'), ('RESOLVIDO', 'Resolvido')], db_index=True, default='ABERTO', max_length=20, verbose_name='Status')),
                ('aberto_em', models.DateTimeField(editable=False, verbose_name='Aberto em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('aberto_por', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='chamados_abertos', to=settings.AUTH_USER_MODEL, verbose_name='Aberto por')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chamados_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável (Quality)')),
                ('responsavel_inteligencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chamados_inteligencia', to=settings.AUTH_USER_MODEL, verbose_name='Responsável (Inteligência)')),
            ],
            options={
                'verbose_name': 'Chamado',
                'verbose_name_plural': 'Chamados',
                'ordering': ['-aberto_em'],
            },
        ),
        migrations.CreateModel(
            name='ChamadoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('ABRIR', 'Abrir'), ('INICIAR_ANALISE', 'Iniciar análise'), ('ENCAMINHAR', 'Encaminhar'), ('FINALIZAR', 'Finalizar'), ('RESOLVER', 'Resolver'), ('BLOQUEAR', 'Bloquear'), ('REABRIR', 'Reabrir')], max_length=20, verbose_name='Ação')),
                ('estado_origem', models.CharField(blank=True, choices=[('ABERTO', 'Aberto'), ('EM_ANALISE', 'Em análise'), ('ENCAMINHADO', 'Encaminhado'), ('BLOQUEADO', 'Bloqueado'), ('RESOLVIDO', 'Resolvido')], max_length=20, null=True, verbose_name='Estado de origem')),
                ('estado_destino', models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ANALISE', 'Em análise'), ('ENCAMINHADO', 'Encaminhado'), ('BLOQUEADO', 'Bloqueado'), ('RESOLVIDO', 'Resolvido')], max_length=20, verbose_name='Estado de destino')),
                ('procedimento_snapshot', models.TextField(blank=True, null=True, verbose_name='Procedimento (snapshot)')),
                ('tratativa_snapshot', models.TextField(blank=True, null=True, verbose_name='Tratativa (snapshot)')),
                ('motivo', models.TextField(blank=True, null=True, verbose_name='Motivo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_chamado', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='chamados.chamado', verbose_name='Chamado')),
                ('responsavel_inteligencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos_encaminhados', to=settings.AUTH_USER_MODEL, verbose_name='Responsável (Inteligência)')),
            ],
            options={
                'verbose_name': 'Evento de chamado',
                'verbose_name_plural': 'Eventos de chamado',
                'ordering': ['criado_em'],
            },
        ),
    ]
