# Generated by Django 6.0 on 2026-07-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0002_grupos_quality_inteligencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('ENCAMINHADO', 'Encaminhado'), ('BLOQUEADO', 'Bloqueado'), ('RESOLVIDO', 'Resolvido')], db_index=True, default='ABERTO', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='chamadoevento',
            name='acao',
            field=models.CharField(choices=[('ABRIR', 'Abrir'), ('ENCAMINHAR', 'Encaminhar'), ('FINALIZAR', 'Finalizar'), ('RESOLVER', 'Resolver'), ('BLOQUEAR', 'Bloquear'), ('REABRIR', 'Reabrir')], max_length=20, verbose_name='Ação'),
        ),
        migrations.AlterField(
            model_name='chamadoevento',
            name='estado_destino',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('ENCAMINHADO', 'Encaminhado'), ('BLOQUEADO', 'Bloqueado'), ('RESOLVIDO', 'Resolvido')], max_length=20, verbose_name='Estado de destino'),
        ),
        migrations.AlterField(
            model_name='chamadoevento',
            name='estado_origem',
            field=models.CharField(blank=True, choices=[('ABERTO', 'Aberto'), ('ENCAMINHADO', 'Encaminhado'), ('BLOQUEADO', 'Bloqueado'), ('RESOLVIDO', 'Resolvido')], max_length=20, null=True, verbose_name='Estado de origem'),
        ),
    ]
