# Generated by Django 6.0 on 2026-07-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0007_modelo_equipamento_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='numero_equipamento',
            field=models.CharField(max_length=500, verbose_name='Nº do equipamento'),
        ),
    ]
