# Generated by Django 6.0 on 2026-07-13 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0011_fluxo_comercial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TratativaEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_equipamento', models.CharField(max_length=60, verbose_name='Nº do equipamento')),
                ('tratativa', models.TextField(verbose_name='Tratativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tratativas_equipamento', to='chamados.chamado', verbose_name='Chamado')),
            ],
            options={
                'verbose_name': 'Tratativa de equipamento',
                'verbose_name_plural': 'Tratativas de equipamento',
                'ordering': ['id'],
            },
        ),
    ]
