# Generated by Django 6.0 on 2026-07-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0012_tratativa_equipamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratativaequipamento',
            name='custo',
            field=models.CharField(blank=True, choices=[('COM_CUSTO', 'Com custo'), ('SEM_CUSTO', 'Sem custo')], max_length=20, verbose_name='Custo'),
        ),
        migrations.AddField(
            model_name='tratativaequipamento',
            name='tratativa_comercial',
            field=models.TextField(blank=True, verbose_name='Tratativa (comercial)'),
        ),
        migrations.AlterField(
            model_name='chamadoevento',
            name='acao',
            field=models.CharField(choices=[('ABRIR', 'Abrir'), ('ENCAMINHAR', 'Encaminhar'), ('ENCAMINHAR_EXPEDICAO', 'Encaminhar para expedição'), ('MARCAR_CHEGADA', 'Marcar chegada'), ('ENCAMINHAR_COMERCIAL', 'Encaminhar para comercial'), ('FINALIZAR_COMERCIAL', 'Finalizar chamado'), ('FINALIZAR', 'Finalizar'), ('RESOLVER', 'Resolver'), ('BLOQUEAR', 'Bloquear'), ('REABRIR', 'Reabrir')], max_length=20, verbose_name='Ação'),
        ),
        migrations.AlterField(
            model_name='tratativaequipamento',
            name='tratativa',
            field=models.TextField(verbose_name='Tratativa (laboratório)'),
        ),
    ]
