# Generated by Django 6.0 on 2026-07-23 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0013_finalizacao_comercial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamadoevento',
            name='acao',
            field=models.CharField(choices=[('ABRIR', 'Abrir'), ('ACEITAR_TRATATIVA', 'Aceitar tratativa'), ('ENCAMINHAR', 'Encaminhar'), ('ENCAMINHAR_EXPEDICAO', 'Encaminhar para expedição'), ('MARCAR_CHEGADA', 'Marcar chegada'), ('ENCAMINHAR_COMERCIAL', 'Encaminhar para comercial'), ('FINALIZAR_COMERCIAL', 'Finalizar chamado'), ('FINALIZAR', 'Finalizar'), ('RESOLVER', 'Resolver'), ('BLOQUEAR', 'Bloquear'), ('REABRIR', 'Reabrir')], max_length=20, verbose_name='Ação'),
        ),
        migrations.CreateModel(
            name='PassagemSetor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(choices=[('QUALITY', 'Quality'), ('INTELIGENCIA', 'Inteligência'), ('EXPEDICAO', 'Expedição'), ('LABORATORIO', 'Laboratório'), ('COMERCIAL', 'Comercial')], db_index=True, max_length=20, verbose_name='Setor')),
                ('chegou_em', models.DateTimeField(verbose_name='Chegou em')),
                ('aceito_em', models.DateTimeField(blank=True, null=True, verbose_name='Aceito em')),
                ('finalizado_em', models.DateTimeField(blank=True, null=True, verbose_name='Finalizado em')),
                ('acao_saida', models.CharField(blank=True, choices=[('ABRIR', 'Abrir'), ('ACEITAR_TRATATIVA', 'Aceitar tratativa'), ('ENCAMINHAR', 'Encaminhar'), ('ENCAMINHAR_EXPEDICAO', 'Encaminhar para expedição'), ('MARCAR_CHEGADA', 'Marcar chegada'), ('ENCAMINHAR_COMERCIAL', 'Encaminhar para comercial'), ('FINALIZAR_COMERCIAL', 'Finalizar chamado'), ('FINALIZAR', 'Finalizar'), ('RESOLVER', 'Resolver'), ('BLOQUEAR', 'Bloquear'), ('REABRIR', 'Reabrir')], max_length=25, verbose_name='Ação de saída')),
                ('aceito_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='passagens_aceitas', to=settings.AUTH_USER_MODEL, verbose_name='Aceito por')),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passagens', to='chamados.chamado', verbose_name='Chamado')),
                ('finalizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='passagens_finalizadas', to=settings.AUTH_USER_MODEL, verbose_name='Finalizado por')),
            ],
            options={
                'verbose_name': 'Passagem por setor (SLA)',
                'verbose_name_plural': 'Passagens por setor (SLA)',
                'ordering': ['id'],
            },
        ),
    ]
