# Generated by Django 6.0 on 2026-07-23 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0015_backfill_passagens'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamadoevento',
            name='acao',
            field=models.CharField(choices=[('ABRIR', 'Abrir'), ('ACEITAR_TRATATIVA', 'Aceitar tratativa'), ('ENCAMINHAR', 'Encaminhar'), ('ENCAMINHAR_EXPEDICAO', 'Encaminhar para expedição'), ('MARCAR_CHEGADA', 'Marcar chegada'), ('REGISTRAR_CONTATO', 'Registrar contato'), ('ENCAMINHAR_COMERCIAL', 'Encaminhar para comercial'), ('FINALIZAR_COMERCIAL', 'Finalizar chamado'), ('FINALIZAR', 'Finalizar'), ('RESOLVER', 'Resolver'), ('BLOQUEAR', 'Bloquear'), ('REABRIR', 'Reabrir')], max_length=20, verbose_name='Ação'),
        ),
        migrations.AlterField(
            model_name='passagemsetor',
            name='acao_saida',
            field=models.CharField(blank=True, choices=[('ABRIR', 'Abrir'), ('ACEITAR_TRATATIVA', 'Aceitar tratativa'), ('ENCAMINHAR', 'Encaminhar'), ('ENCAMINHAR_EXPEDICAO', 'Encaminhar para expedição'), ('MARCAR_CHEGADA', 'Marcar chegada'), ('REGISTRAR_CONTATO', 'Registrar contato'), ('ENCAMINHAR_COMERCIAL', 'Encaminhar para comercial'), ('FINALIZAR_COMERCIAL', 'Finalizar chamado'), ('FINALIZAR', 'Finalizar'), ('RESOLVER', 'Resolver'), ('BLOQUEAR', 'Bloquear'), ('REABRIR', 'Reabrir')], max_length=25, verbose_name='Ação de saída'),
        ),
        migrations.CreateModel(
            name='ContatoExpedicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_contato', models.CharField(max_length=120, verbose_name='Pessoa contatada')),
                ('telefone', models.CharField(blank=True, max_length=30, verbose_name='Telefone')),
                ('tratativa', models.TextField(verbose_name='Tratativa do contato')),
                ('codigo_rastreio', models.CharField(blank=True, max_length=60, verbose_name='Código de rastreio')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contatos_expedicao', to='chamados.chamado', verbose_name='Chamado')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contatos_expedicao', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Contato da expedição',
                'verbose_name_plural': 'Contatos da expedição',
                'ordering': ['-criado_em'],
            },
        ),
    ]
