# Generated by Django 6.0 on 2026-07-24 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0016_contato_expedicao'),
        ('registrodemanutencao', '0026_alter_registrodemanutencao_data_criacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='manutencao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chamados', to='registrodemanutencao.registrodemanutencao', verbose_name='Manutenção vinculada'),
        ),
    ]
