# Generated by Django 6.0 on 2026-07-24 00:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0017_vinculo_manutencao'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='termo_substituicao',
            field=models.FileField(blank=True, null=True, upload_to='chamados/termos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Termo de substituição (PDF)'),
        ),
    ]
