# Generated by Django 6.0 on 2026-07-24 01:02

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def _criar_grupo_financeiro(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.get_or_create(name="financeiro")


def _remover_grupo_financeiro(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name="financeiro").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0018_termo_substituicao'),
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(_criar_grupo_financeiro, _remover_grupo_financeiro),
        migrations.AddField(
            model_name='chamado',
            name='nota_fiscal',
            field=models.CharField(blank=True, max_length=60, verbose_name='Nota fiscal (NF)'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='valor_faturamento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valor do faturamento'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('ENCAMINHADO', 'Encaminhado'), ('EXPEDICAO', 'Expedição'), ('LABORATORIO', 'Laboratório'), ('COMERCIAL', 'Comercial'), ('FINANCEIRO', 'Financeiro'), ('BLOQUEADO', 'Bloqueado'), ('RESOLVIDO', 'Resolvido')], db_index=True, default='ABERTO', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='chamadoevento',
            name='acao',
            field=models.CharField(choices=[('ABRIR', 'Abrir'), ('ACEITAR_TRATATIVA', 'Aceitar tratativa'), ('ENCAMINHAR', 'Encaminhar'), ('ENCAMINHAR_EXPEDICAO', 'Encaminhar para expedição'), ('MARCAR_CHEGADA', 'Marcar chegada'), ('REGISTRAR_CONTATO', 'Registrar contato'), ('ENCAMINHAR_COMERCIAL', 'Encaminhar para comercial'), ('FINALIZAR_COMERCIAL', 'Finalizar chamado'), ('FATURAR', 'Faturado'), ('FINALIZAR', 'Finalizar'), ('RESOLVER', 'Resolver'), ('BLOQUEAR', 'Bloquear'), ('REABRIR', 'Reabrir')], max_length=20, verbose_name='Ação'),
        ),
        migrations.AlterField(
            model_name='chamadoevento',
            name='estado_destino',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('ENCAMINHADO', 'Encaminhado'), ('EXPEDICAO', 'Expedição'), ('LABORATORIO', 'Laboratório'), ('COMERCIAL', 'Comercial'), ('FINANCEIRO', 'Financeiro'), ('BLOQUEADO', 'Bloqueado'), ('RESOLVIDO', 'Resolvido')], max_length=20, verbose_name='Estado de destino'),
        ),
        migrations.AlterField(
            model_name='chamadoevento',
            name='estado_origem',
            field=models.CharField(blank=True, choices=[('ABERTO', 'Aberto'), ('ENCAMINHADO', 'Encaminhado'), ('EXPEDICAO', 'Expedição'), ('LABORATORIO', 'Laboratório'), ('COMERCIAL', 'Comercial'), ('FINANCEIRO', 'Financeiro'), ('BLOQUEADO', 'Bloqueado'), ('RESOLVIDO', 'Resolvido')], max_length=20, null=True, verbose_name='Estado de origem'),
        ),
        migrations.AlterField(
            model_name='passagemsetor',
            name='acao_saida',
            field=models.CharField(blank=True, choices=[('ABRIR', 'Abrir'), ('ACEITAR_TRATATIVA', 'Aceitar tratativa'), ('ENCAMINHAR', 'Encaminhar'), ('ENCAMINHAR_EXPEDICAO', 'Encaminhar para expedição'), ('MARCAR_CHEGADA', 'Marcar chegada'), ('REGISTRAR_CONTATO', 'Registrar contato'), ('ENCAMINHAR_COMERCIAL', 'Encaminhar para comercial'), ('FINALIZAR_COMERCIAL', 'Finalizar chamado'), ('FATURAR', 'Faturado'), ('FINALIZAR', 'Finalizar'), ('RESOLVER', 'Resolver'), ('BLOQUEAR', 'Bloquear'), ('REABRIR', 'Reabrir')], max_length=25, verbose_name='Ação de saída'),
        ),
        migrations.AlterField(
            model_name='passagemsetor',
            name='setor',
            field=models.CharField(choices=[('QUALITY', 'Quality'), ('INTELIGENCIA', 'Inteligência'), ('EXPEDICAO', 'Expedição'), ('LABORATORIO', 'Laboratório'), ('COMERCIAL', 'Comercial'), ('FINANCEIRO', 'Financeiro')], db_index=True, max_length=20, verbose_name='Setor'),
        ),
    ]
