# Generated by Django 6.0 on 2026-09-30 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0020_chamado_equipamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamado',
            name='modelo_equipamento',
        ),
    ]
