# Generated by Django 6.0 on 2026-10-01 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0021_remove_modelo_equipamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamadoequipamento',
            name='customizacao',
            field=models.CharField(blank=True, choices=[('Sem custumização', 'Sem custumização'), ('Caixa de papelão', 'Caixa de papelão'), ('Caixa de papelão (bateria desacoplada)', 'Caixa de papelão (bateria desacoplada)'), ('Caixa de papelão + DF', 'Caixa de papelão + DF'), ('Termo branco', 'Termo branco'), ('Termo branco + Imã', 'Termo branco + Imã'), ('Termo branco + D.F', 'Termo branco + D.F'), ('Termo branco slim', 'Termo branco slim'), ('Termo branco slim + D.F +EQT', 'Termo branco slim + D.F +EQT'), ('Termo cinza slim + D.F +EQT', 'Termo cinza slim + D.F +EQT'), ('Termo branco (isopor)', 'Termo branco (isopor)'), ('Termo branco - bateria externa', 'Termo branco - bateria externa'), ('Termo marrom + imã', 'Termo marrom + imã'), ('Termo cinza', 'Termo cinza'), ('Termo cinza + imã', 'Termo cinza + imã'), ('Termo preto', 'Termo preto'), ('Termo preto + imã', 'Termo preto + imã'), ('Termo brabco |marrim-slim', 'Termo brabco |marrim-slim'), ('Termo marrom slim +D.F + EQT', 'Termo marrom slim +D.F + EQT'), ('Termo marrom', 'Termo marrom'), ('Caixa blindada', 'Caixa blindada'), ('Tênis/ Sapato', 'Tênis/ Sapato'), ('Projetor', 'Projetor'), ('Caixa de som', 'Caixa de som'), ('Luminaria', 'Luminaria'), ('Alexa', 'Alexa'), ('Video Game', 'Video Game'), ('Secador de cabelo', 'Secador de cabelo'), ('Roteador', 'Roteador'), ('Relogio digital', 'Relogio digital')], default='', max_length=250, verbose_name='Customização'),
        ),
        migrations.AddField(
            model_name='chamadoequipamento',
            name='tipo_contrato',
            field=models.CharField(blank=True, choices=[('Descartavel', 'Descartavel'), ('Retornavel', 'Retornavel')], default='', max_length=50, verbose_name='Tipo de contrato'),
        ),
        migrations.AddField(
            model_name='tratativaequipamento',
            name='destino',
            field=models.CharField(blank=True, choices=[('SUBSTITUICAO', 'Substituição'), ('DEVOLUCAO', 'Devolução')], max_length=20, verbose_name='Destino'),
        ),
    ]
