# Generated by Django 6.0 on 2026-10-02 12:13

import django.db.models.deletion
from django.db import migrations, models


def _criar_grupos(apps, schema_editor):
    """Recepção é grupo novo; CONFIGURACAO já existe (time das requisições) e é
    reaproveitado — get_or_create cobre bancos onde ele ainda não exista."""
    Group = apps.get_model("auth", "Group")
    for nome in ("recepcao", "CONFIGURACAO"):
        Group.objects.get_or_create(name=nome)


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0022_equipamento_customizacao_contrato_destino'),
        # A FK só precisa da tabela de requisições (criada na primeira migração do
        # app); '__first__' também funciona quando os testes desligam as migrações
        # do requisicao (MIGRATION_MODULES = None).
        ('requisicao', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='codigo_rastreio_envio',
            field=models.CharField(blank=True, max_length=100, verbose_name='Código de rastreio (envio)'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='data_envio',
            field=models.DateField(blank=True, null=True, verbose_name='Data de envio'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='metodo_envio',
            field=models.CharField(blank=True, choices=[('Agente', 'Agente'), ('Retirada na base', 'Retirada na base'), ('Motoboy', 'Motoboy'), ('transportadora', 'Transportadora'), ('Correio', 'Correio'), ('Comercial', 'Comercial')], max_length=50, verbose_name='Método de envio'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='requisicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chamados', to='requisicao.requisicoes', verbose_name='Requisição de substituição'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('ENCAMINHADO', 'Encaminhado'), ('EXPEDICAO', 'Expedição'), ('LABORATORIO', 'Laboratório'), ('COMERCIAL', 'Comercial'), ('FINANCEIRO', 'Financeiro'), ('RECEPCAO', 'Recepção'), ('CONFIGURACAO', 'Configuração'), ('ENVIO', 'Envio (Expedição)'), ('BLOQUEADO', 'Bloqueado'), ('RESOLVIDO', 'Resolvido')], db_index=True, default='ABERTO', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='chamadoevento',
            name='acao',
            field=models.CharField(choices=[('ABRIR', 'Abrir'), ('ACEITAR_TRATATIVA', 'Aceitar tratativa'), ('ENCAMINHAR', 'Encaminhar'), ('ENCAMINHAR_EXPEDICAO', 'Encaminhar para expedição'), ('MARCAR_CHEGADA', 'Marcar chegada'), ('REGISTRAR_CONTATO', 'Registrar contato'), ('ENCAMINHAR_COMERCIAL', 'Encaminhar para comercial'), ('FINALIZAR_COMERCIAL', 'Finalizar chamado'), ('FATURAR', 'Faturado'), ('ENCAMINHAR_CONFIGURACAO', 'Encaminhar para configuração'), ('ENCAMINHAR_ENVIO', 'Encaminhar para expedição'), ('REGISTRAR_ENVIO', 'Registrar envio'), ('CONFIRMAR_ENCERRAMENTO', 'Confirmar encerramento'), ('FINALIZAR', 'Finalizar'), ('RESOLVER', 'Resolver'), ('BLOQUEAR', 'Bloquear'), ('REABRIR', 'Reabrir')], max_length=30, verbose_name='Ação'),
        ),
        migrations.AlterField(
            model_name='chamadoevento',
            name='estado_destino',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('ENCAMINHADO', 'Encaminhado'), ('EXPEDICAO', 'Expedição'), ('LABORATORIO', 'Laboratório'), ('COMERCIAL', 'Comercial'), ('FINANCEIRO', 'Financeiro'), ('RECEPCAO', 'Recepção'), ('CONFIGURACAO', 'Configuração'), ('ENVIO', 'Envio (Expedição)'), ('BLOQUEADO', 'Bloqueado'), ('RESOLVIDO', 'Resolvido')], max_length=20, verbose_name='Estado de destino'),
        ),
        migrations.AlterField(
            model_name='chamadoevento',
            name='estado_origem',
            field=models.CharField(blank=True, choices=[('ABERTO', 'Aberto'), ('ENCAMINHADO', 'Encaminhado'), ('EXPEDICAO', 'Expedição'), ('LABORATORIO', 'Laboratório'), ('COMERCIAL', 'Comercial'), ('FINANCEIRO', 'Financeiro'), ('RECEPCAO', 'Recepção'), ('CONFIGURACAO', 'Configuração'), ('ENVIO', 'Envio (Expedição)'), ('BLOQUEADO', 'Bloqueado'), ('RESOLVIDO', 'Resolvido')], max_length=20, null=True, verbose_name='Estado de origem'),
        ),
        migrations.AlterField(
            model_name='passagemsetor',
            name='acao_saida',
            field=models.CharField(blank=True, choices=[('ABRIR', 'Abrir'), ('ACEITAR_TRATATIVA', 'Aceitar tratativa'), ('ENCAMINHAR', 'Encaminhar'), ('ENCAMINHAR_EXPEDICAO', 'Encaminhar para expedição'), ('MARCAR_CHEGADA', 'Marcar chegada'), ('REGISTRAR_CONTATO', 'Registrar contato'), ('ENCAMINHAR_COMERCIAL', 'Encaminhar para comercial'), ('FINALIZAR_COMERCIAL', 'Finalizar chamado'), ('FATURAR', 'Faturado'), ('ENCAMINHAR_CONFIGURACAO', 'Encaminhar para configuração'), ('ENCAMINHAR_ENVIO', 'Encaminhar para expedição'), ('REGISTRAR_ENVIO', 'Registrar envio'), ('CONFIRMAR_ENCERRAMENTO', 'Confirmar encerramento'), ('FINALIZAR', 'Finalizar'), ('RESOLVER', 'Resolver'), ('BLOQUEAR', 'Bloquear'), ('REABRIR', 'Reabrir')], max_length=25, verbose_name='Ação de saída'),
        ),
        migrations.AlterField(
            model_name='passagemsetor',
            name='setor',
            field=models.CharField(choices=[('QUALITY', 'Quality'), ('INTELIGENCIA', 'Inteligência'), ('EXPEDICAO', 'Expedição'), ('LABORATORIO', 'Laboratório'), ('COMERCIAL', 'Comercial'), ('FINANCEIRO', 'Financeiro'), ('RECEPCAO', 'Recepção'), ('CONFIGURACAO', 'Configuração')], db_index=True, max_length=20, verbose_name='Setor'),
        ),
        migrations.RunPython(_criar_grupos, migrations.RunPython.noop),
    ]
