# Generated by Django 6.0 on 2026-07-31 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoIscas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raio_padrao_km', models.PositiveIntegerField(default=50, verbose_name='Raio padrão de busca (km)')),
                ('dias_alerta_retornavel', models.PositiveIntegerField(default=90, help_text='Retornável com cliente há mais dias que isto é sinalizado (ISC-RF-33).', verbose_name='Alerta de retornável em posse (dias)')),
                ('saldo_minimo_alerta', models.PositiveIntegerField(default=5, help_text='Agente com saldo abaixo disto aparece no dashboard (ISC-RF-38).', verbose_name='Saldo mínimo antes do alerta')),
                ('horas_alerta_em_rota', models.PositiveIntegerField(default=24, help_text='Atribuição parada em EM_ROTA por mais que isto vira pendência.', verbose_name='Alerta de atribuição em rota (horas)')),
                ('tiles_url', models.CharField(default='https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', max_length=300, verbose_name='URL dos tiles')),
                ('tiles_atribuicao', models.CharField(default='© OpenStreetMap contributors', help_text='Obrigatória pela política de uso do OpenStreetMap.', max_length=300, verbose_name='Atribuição dos tiles')),
            ],
            options={
                'verbose_name': 'Configuração do Iscas Fast',
                'verbose_name_plural': 'Configuração do Iscas Fast',
            },
        ),
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('logradouro', models.CharField(max_length=200, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=20, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('geo_origem', models.CharField(default='PENDENTE', max_length=20, verbose_name='Origem da coordenada')),
                ('geocodificado_em', models.DateTimeField(blank=True, null=True, verbose_name='Geocodificado em')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Depósito',
                'verbose_name_plural': 'Depósitos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='GeocodeCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco_hash', models.CharField(max_length=64, unique=True, verbose_name='Hash do endereço')),
                ('endereco_normalizado', models.CharField(max_length=300, verbose_name='Endereço normalizado')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude')),
                ('provedor', models.CharField(default='nominatim', max_length=50, verbose_name='Provedor')),
                ('consultado_em', models.DateTimeField(auto_now_add=True, verbose_name='Consultado em')),
            ],
            options={
                'verbose_name': 'Cache de geocodificação',
                'verbose_name_plural': 'Cache de geocodificação',
                'ordering': ['-consultado_em'],
            },
        ),
        migrations.CreateModel(
            name='ModeloEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('fabricante', models.CharField(blank=True, max_length=120, verbose_name='Fabricante')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('DESCARTAVEL', 'Descartável'), ('RETORNAVEL', 'Retornável')], max_length=20, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Modelo de equipamento',
                'verbose_name_plural': 'Modelos de equipamento',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('logradouro', models.CharField(max_length=200, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=20, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('geo_origem', models.CharField(default='PENDENTE', max_length=20, verbose_name='Origem da coordenada')),
                ('geocodificado_em', models.DateTimeField(blank=True, null=True, verbose_name='Geocodificado em')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('cpf_cifrado', models.TextField(blank=True, verbose_name='CPF (cifrado)')),
                ('cpf_hash', models.CharField(help_text='SHA-256 com pepper; garante unicidade sem decifrar.', max_length=64, unique=True, verbose_name='CPF (hash)')),
                ('telefone', models.CharField(max_length=30, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
            ],
            options={
                'verbose_name': 'Agente',
                'verbose_name_plural': 'Agentes',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='iscas_agente_latlng'), models.Index(fields=['is_active', 'nome'], name='iscas_agente_ativo_nome')],
            },
        ),
        migrations.CreateModel(
            name='Atribuicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('status', models.CharField(choices=[('RESERVADA', 'Reservada'), ('EM_ROTA', 'Em rota'), ('ENTREGUE', 'Entregue'), ('CANCELADA', 'Cancelada')], default='RESERVADA', max_length=20, verbose_name='Status')),
                ('em_rota_em', models.DateTimeField(blank=True, null=True, verbose_name='Em rota em')),
                ('entregue_em', models.DateTimeField(blank=True, null=True, verbose_name='Entregue em')),
                ('recebido_por', models.CharField(blank=True, max_length=150, verbose_name='Recebido por')),
                ('motivo_cancelamento', models.TextField(blank=True, verbose_name='Motivo do cancelamento')),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atribuicoes', to='iscas.agente', verbose_name='Agente')),
                ('criada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atribuicoes_iscas', to=settings.AUTH_USER_MODEL, verbose_name='Criada por')),
            ],
            options={
                'verbose_name': 'Atribuição',
                'verbose_name_plural': 'Atribuições',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('logradouro', models.CharField(max_length=200, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=20, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('geo_origem', models.CharField(default='PENDENTE', max_length=20, verbose_name='Origem da coordenada')),
                ('geocodificado_em', models.DateTimeField(blank=True, null=True, verbose_name='Geocodificado em')),
                ('nome_razao_social', models.CharField(max_length=200, verbose_name='Nome / Razão social')),
                ('documento', models.CharField(blank=True, max_length=20, verbose_name='Documento')),
                ('tipo_documento', models.CharField(choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ')], default='CNPJ', max_length=4, verbose_name='Tipo de documento')),
                ('contato_nome', models.CharField(blank=True, max_length=120, verbose_name='Contato')),
                ('telefone', models.CharField(blank=True, max_length=30, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome_razao_social'],
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='iscas_cliente_latlng'), models.Index(fields=['is_active', 'nome_razao_social'], name='iscas_cli_ativo_nome')],
            },
        ),
        migrations.CreateModel(
            name='Custodia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('tipo', models.CharField(choices=[('EXTERNO', 'Externo'), ('DEPOSITO', 'Depósito'), ('AGENTE', 'Agente'), ('CLIENTE', 'Cliente'), ('MANUTENCAO', 'Manutenção'), ('BAIXA', 'Baixa')], max_length=20, verbose_name='Tipo')),
                ('descricao', models.CharField(blank=True, max_length=200, verbose_name='Descrição')),
                ('agente', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custodia', to='iscas.agente', verbose_name='Agente')),
                ('cliente', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custodia', to='iscas.cliente', verbose_name='Cliente')),
                ('deposito', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custodia', to='iscas.deposito', verbose_name='Depósito')),
            ],
            options={
                'verbose_name': 'Custódia',
                'verbose_name_plural': 'Custódias',
                'ordering': ['tipo'],
            },
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('ATRIBUIDA', 'Atribuída'), ('EM_ROTA', 'Em rota'), ('ENTREGUE', 'Entregue'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=20, verbose_name='Status')),
                ('aberta_em', models.DateTimeField(verbose_name='Aberta em')),
                ('prazo_desejado', models.DateField(blank=True, null=True, verbose_name='Prazo desejado')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('motivo_cancelamento', models.TextField(blank=True, verbose_name='Motivo do cancelamento')),
                ('aberta_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_iscas', to=settings.AUTH_USER_MODEL, verbose_name='Aberta por')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes', to='iscas.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Solicitação',
                'verbose_name_plural': 'Solicitações',
                'ordering': ['-aberta_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('TRANSFERENCIA', 'Transferência'), ('ENTREGA', 'Entrega'), ('RETORNO', 'Retorno'), ('ENVIO_MANUTENCAO', 'Envio para manutenção'), ('RETORNO_MANUTENCAO', 'Retorno de manutenção'), ('BAIXA', 'Baixa'), ('ESTORNO', 'Estorno')], max_length=25, verbose_name='Tipo')),
                ('ocorrido_em', models.DateTimeField(verbose_name='Ocorrido em')),
                ('justificativa', models.TextField(blank=True, verbose_name='Justificativa')),
                ('motivo_baixa', models.CharField(blank=True, choices=[('PERDA', 'Perda'), ('AVARIA', 'Avaria'), ('OBSOLESCENCIA', 'Obsolescência')], max_length=20, verbose_name='Motivo da baixa')),
                ('nota_fiscal', models.CharField(blank=True, max_length=50, verbose_name='Nota fiscal')),
                ('lote', models.CharField(blank=True, max_length=50, verbose_name='Lote')),
                ('atribuicao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='iscas.atribuicao', verbose_name='Atribuição')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_iscas', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_entrada', to='iscas.custodia', verbose_name='Destino')),
                ('estorno_de', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estornos', to='iscas.movimentacao', verbose_name='Estorno de')),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_saida', to='iscas.custodia', verbose_name='Origem')),
                ('solicitacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='iscas.solicitacao', verbose_name='Solicitação')),
            ],
            options={
                'verbose_name': 'Movimentação',
                'verbose_name_plural': 'Movimentações',
                'ordering': ['-ocorrido_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ItemSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_solicitacao', to='iscas.modeloequipamento', verbose_name='Modelo')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='iscas.solicitacao', verbose_name='Solicitação')),
            ],
            options={
                'verbose_name': 'Item da solicitação',
                'verbose_name_plural': 'Itens da solicitação',
            },
        ),
        migrations.AddField(
            model_name='atribuicao',
            name='solicitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atribuicoes', to='iscas.solicitacao', verbose_name='Solicitação'),
        ),
        migrations.CreateModel(
            name='SolicitacaoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('status_anterior', models.CharField(blank=True, max_length=20, verbose_name='Status anterior')),
                ('status_novo', models.CharField(max_length=20, verbose_name='Status novo')),
                ('dados', models.JSONField(blank=True, default=dict, verbose_name='Dados')),
                ('atribuicao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='iscas.atribuicao', verbose_name='Atribuição')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_iscas', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='iscas.solicitacao', verbose_name='Solicitação')),
            ],
            options={
                'verbose_name': 'Evento de solicitação',
                'verbose_name_plural': 'Eventos de solicitação',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=100, unique=True, verbose_name='Identificador')),
                ('identificador_gerado', models.BooleanField(default=False, help_text='True quando a unidade não trouxe identificador de fábrica (ISC-RF-09).', verbose_name='Identificador gerado pelo sistema')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('custodia_desde', models.DateTimeField(verbose_name='Em custódia desde')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
                ('custodia_atual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidades', to='iscas.custodia', verbose_name='Custódia atual')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidades', to='iscas.modeloequipamento', verbose_name='Modelo')),
                ('ultima_movimentacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidades_apontadas', to='iscas.movimentacao', verbose_name='Última movimentação')),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
                'ordering': ['identificador'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoUnidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('movimentacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='linhas', to='iscas.movimentacao', verbose_name='Movimentação')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='iscas.unidade', verbose_name='Unidade')),
            ],
            options={
                'verbose_name': 'Linha de movimentação',
                'verbose_name_plural': 'Linhas de movimentação',
            },
        ),
        migrations.CreateModel(
            name='AtribuicaoUnidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservada_em', models.DateTimeField(auto_now_add=True, verbose_name='Reservada em')),
                ('liberada_em', models.DateTimeField(blank=True, null=True, verbose_name='Liberada em')),
                ('atribuicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='iscas.atribuicao', verbose_name='Atribuição')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='iscas.unidade', verbose_name='Unidade')),
            ],
            options={
                'verbose_name': 'Reserva de unidade',
                'verbose_name_plural': 'Reservas de unidade',
            },
        ),
        migrations.AddConstraint(
            model_name='custodia',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tipo', 'AGENTE'), ('agente__isnull', False), ('cliente__isnull', True), ('deposito__isnull', True)), models.Q(('tipo', 'CLIENTE'), ('agente__isnull', True), ('cliente__isnull', False), ('deposito__isnull', True)), models.Q(('tipo', 'DEPOSITO'), ('agente__isnull', True), ('cliente__isnull', True), ('deposito__isnull', False)), models.Q(('tipo__in', ('EXTERNO', 'MANUTENCAO', 'BAIXA')), ('agente__isnull', True), ('cliente__isnull', True), ('deposito__isnull', True)), _connector='OR'), name='iscas_custodia_vinculo_coerente'),
        ),
        migrations.AddConstraint(
            model_name='custodia',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo__in', ('EXTERNO', 'MANUTENCAO', 'BAIXA'))), fields=('tipo',), name='iscas_custodia_singleton_unica'),
        ),
        migrations.AddIndex(
            model_name='solicitacao',
            index=models.Index(fields=['status', '-aberta_em'], name='iscas_sol_status_data'),
        ),
        migrations.AddIndex(
            model_name='solicitacao',
            index=models.Index(fields=['cliente', '-aberta_em'], name='iscas_sol_cliente'),
        ),
        migrations.AddIndex(
            model_name='movimentacao',
            index=models.Index(fields=['-ocorrido_em'], name='iscas_mov_ocorrido'),
        ),
        migrations.AddIndex(
            model_name='movimentacao',
            index=models.Index(fields=['tipo', '-ocorrido_em'], name='iscas_mov_tipo_data'),
        ),
        migrations.AddIndex(
            model_name='movimentacao',
            index=models.Index(fields=['origem', '-ocorrido_em'], name='iscas_mov_origem'),
        ),
        migrations.AddIndex(
            model_name='movimentacao',
            index=models.Index(fields=['destino', '-ocorrido_em'], name='iscas_mov_destino'),
        ),
        migrations.AddConstraint(
            model_name='movimentacao',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tipo', 'BAIXA'), models.Q(('motivo_baixa', ''), _negated=True)), models.Q(models.Q(('tipo', 'BAIXA'), _negated=True), ('motivo_baixa', '')), _connector='OR'), name='iscas_mov_baixa_exige_motivo'),
        ),
        migrations.AddConstraint(
            model_name='movimentacao',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estorno_de__isnull', False), ('tipo', 'ESTORNO')), models.Q(models.Q(('tipo', 'ESTORNO'), _negated=True), ('estorno_de__isnull', True)), _connector='OR'), name='iscas_mov_estorno_referencia'),
        ),
        migrations.AddConstraint(
            model_name='movimentacao',
            constraint=models.CheckConstraint(condition=models.Q(('origem', models.F('destino')), _negated=True), name='iscas_mov_origem_difere_destino'),
        ),
        migrations.AddConstraint(
            model_name='itemsolicitacao',
            constraint=models.UniqueConstraint(fields=('solicitacao', 'modelo'), name='iscas_item_modelo_unico'),
        ),
        migrations.AddConstraint(
            model_name='itemsolicitacao',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade__gt', 0)), name='iscas_item_qtd_positiva'),
        ),
        migrations.AddIndex(
            model_name='atribuicao',
            index=models.Index(fields=['agente', 'status'], name='iscas_atrib_agente_status'),
        ),
        migrations.AddIndex(
            model_name='atribuicao',
            index=models.Index(fields=['solicitacao', 'status'], name='iscas_atrib_sol_status'),
        ),
        migrations.AddIndex(
            model_name='solicitacaoevento',
            index=models.Index(fields=['solicitacao', '-created_at'], name='iscas_evt_sol'),
        ),
        migrations.AddIndex(
            model_name='unidade',
            index=models.Index(fields=['custodia_atual', 'modelo', 'custodia_desde'], name='iscas_unid_cust_mod'),
        ),
        migrations.AddIndex(
            model_name='movimentacaounidade',
            index=models.Index(fields=['unidade', 'movimentacao'], name='iscas_movunid_extrato'),
        ),
        migrations.AddConstraint(
            model_name='movimentacaounidade',
            constraint=models.UniqueConstraint(fields=('movimentacao', 'unidade'), name='iscas_movunid_unica'),
        ),
        migrations.AddIndex(
            model_name='atribuicaounidade',
            index=models.Index(fields=['atribuicao', 'liberada_em'], name='iscas_reserva_atrib'),
        ),
        migrations.AddConstraint(
            model_name='atribuicaounidade',
            constraint=models.UniqueConstraint(condition=models.Q(('liberada_em__isnull', True)), fields=('unidade',), name='iscas_reserva_ativa_unica'),
        ),
    ]
