# Generated by Django 6.0 on 2026-08-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iscas', '0002_custodias_singleton'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='comercial_responsavel',
            field=models.CharField(blank=True, help_text='Quem atende esta conta no comercial da Golden Sat.', max_length=120, verbose_name='Comercial responsável'),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='comercial_responsavel',
            field=models.CharField(blank=True, max_length=120, verbose_name='Comercial responsável'),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='contato_nome',
            field=models.CharField(blank=True, max_length=120, verbose_name='Contato'),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='documento',
            field=models.CharField(blank=True, max_length=20, verbose_name='CNPJ / CPF'),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='entrega_bairro',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='entrega_cep',
            field=models.CharField(blank=True, max_length=9, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='entrega_cidade',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='entrega_complemento',
            field=models.CharField(blank=True, max_length=100, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='entrega_logradouro',
            field=models.CharField(blank=True, max_length=200, verbose_name='Logradouro'),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='entrega_numero',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='entrega_uf',
            field=models.CharField(blank=True, max_length=2, verbose_name='UF'),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='telefone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Telefone'),
        ),
    ]
