# Generated by Django 6.0 on 2026-09-02 15:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iscas', '0003_cliente_comercial_responsavel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='entrega_geo_origem',
            field=models.CharField(default='PENDENTE', max_length=20, verbose_name='Origem da coordenada de entrega'),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='entrega_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude da entrega'),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='entrega_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude da entrega'),
        ),
        migrations.AlterField(
            model_name='agente',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='agente',
            name='logradouro',
            field=models.CharField(blank=True, max_length=200, verbose_name='Logradouro'),
        ),
        migrations.AlterField(
            model_name='agente',
            name='uf',
            field=models.CharField(blank=True, max_length=2, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='logradouro',
            field=models.CharField(blank=True, max_length=200, verbose_name='Logradouro'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='uf',
            field=models.CharField(blank=True, max_length=2, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='deposito',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='deposito',
            name='logradouro',
            field=models.CharField(blank=True, max_length=200, verbose_name='Logradouro'),
        ),
        migrations.AlterField(
            model_name='deposito',
            name='uf',
            field=models.CharField(blank=True, max_length=2, verbose_name='UF'),
        ),
        migrations.AddIndex(
            model_name='solicitacao',
            index=models.Index(fields=['entrega_latitude', 'entrega_longitude'], name='iscas_sol_entrega_latlng'),
        ),
    ]
