# Generated by Django 6.0 on 2026-09-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iscas', '0004_solicitacao_entrega_geo_origem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeloequipamento',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código'),
        ),
    ]
