# Generated by Django 6.0 on 2026-09-23 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iscas', '0006_grupos_papeis_iscas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('acao', models.CharField(db_index=True, max_length=100, verbose_name='Ação')),
                ('capacidade', models.CharField(blank=True, choices=[('VER_PAINEL', 'Ver painel'), ('VER_MAPA', 'Ver mapa'), ('VER_SOLICITACAO', 'Ver solicitações'), ('CRIAR_SOLICITACAO', 'Criar solicitação'), ('ATENDER_SOLICITACAO', 'Atender solicitação'), ('EXCLUIR_SOLICITACAO', 'Excluir solicitação'), ('VER_ESTOQUE', 'Ver estoque'), ('MOVIMENTAR_ESTOQUE', 'Movimentar estoque'), ('BAIXAR_MANUTENCAO', 'Dar baixa e manutenção'), ('CADASTRAR_CLIENTE', 'Cadastrar cliente'), ('CADASTRAR_MODELO', 'Cadastrar modelo'), ('CADASTRAR_AGENTE', 'Cadastrar agente'), ('CADASTRAR_DEPOSITO', 'Cadastrar depósito'), ('DESATIVAR_CADASTRO', 'Desativar cadastro'), ('VER_AUDITORIA', 'Ver auditoria'), ('CONSULTAR_APOIO', 'Consultar CEP e endereço')], max_length=40, verbose_name='Capacidade exigida')),
                ('caminho', models.CharField(max_length=255, verbose_name='Caminho')),
                ('alvo', models.JSONField(blank=True, default=dict, verbose_name='Alvo')),
                ('campos', models.JSONField(blank=True, default=list, verbose_name='Campos alterados')),
                ('status_http', models.PositiveSmallIntegerField(verbose_name='Status HTTP')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditoria_iscas', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Registro de auditoria',
                'verbose_name_plural': 'Registros de auditoria',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['-created_at'], name='iscas_aud_data'), models.Index(fields=['autor', '-created_at'], name='iscas_aud_autor'), models.Index(fields=['acao', '-created_at'], name='iscas_aud_acao')],
            },
        ),
    ]
