# Generated by Django 6.0 on 2026-09-23 19:50

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iscas', '0007_registroauditoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='atribuicao',
            name='deposito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atribuicoes', to='iscas.deposito', verbose_name='Depósito da retirada'),
        ),
        migrations.AddField(
            model_name='atribuicao',
            name='origem_tipo',
            field=models.CharField(choices=[('AGENTE', 'Entrega por agente'), ('RETIRADA_BASE', 'Retirada na base')], default='AGENTE', max_length=20, verbose_name='Origem'),
        ),
        migrations.AddField(
            model_name='atribuicao',
            name='valor_agente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor cobrado pelo agente'),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='solicitante_nome',
            field=models.CharField(blank=True, max_length=120, verbose_name='Solicitado por (no cliente)'),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='valor_cliente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor cobrado do cliente'),
        ),
        migrations.AlterField(
            model_name='atribuicao',
            name='agente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atribuicoes', to='iscas.agente', verbose_name='Agente'),
        ),
        migrations.AddIndex(
            model_name='atribuicao',
            index=models.Index(fields=['deposito', 'status'], name='iscas_atrib_dep_status'),
        ),
        migrations.AddConstraint(
            model_name='atribuicao',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('agente__isnull', False), ('deposito__isnull', True), ('origem_tipo', 'AGENTE')), models.Q(('agente__isnull', True), ('deposito__isnull', False), ('origem_tipo', 'RETIRADA_BASE')), _connector='OR'), name='iscas_atrib_origem_xor'),
        ),
        migrations.AddConstraint(
            model_name='atribuicao',
            constraint=models.CheckConstraint(condition=models.Q(('valor_agente__gte', 0), ('valor_agente__isnull', True), _connector='OR'), name='iscas_atrib_valor_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='atribuicao',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('origem_tipo', 'RETIRADA_BASE'), _negated=True), ('valor_agente__isnull', True), _connector='OR'), name='iscas_atrib_retirada_sem_valor'),
        ),
        migrations.AddConstraint(
            model_name='solicitacao',
            constraint=models.CheckConstraint(condition=models.Q(('valor_cliente__gte', 0), ('valor_cliente__isnull', True), _connector='OR'), name='iscas_sol_valor_cliente_nao_negativo'),
        ),
    ]
