# Generated by Django 6.0 on 2026-09-23 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iscas', '0008_valores_e_retirada_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroauditoria',
            name='capacidade',
            field=models.CharField(blank=True, choices=[('VER_PAINEL', 'Ver painel'), ('VER_MAPA', 'Ver mapa'), ('VER_SOLICITACAO', 'Ver solicitações'), ('CRIAR_SOLICITACAO', 'Criar solicitação'), ('ATENDER_SOLICITACAO', 'Atender solicitação'), ('EXCLUIR_SOLICITACAO', 'Excluir solicitação'), ('VER_ESTOQUE', 'Ver estoque'), ('MOVIMENTAR_ESTOQUE', 'Movimentar estoque'), ('BAIXAR_MANUTENCAO', 'Dar baixa e manutenção'), ('CADASTRAR_CLIENTE', 'Cadastrar cliente'), ('CADASTRAR_MODELO', 'Cadastrar modelo'), ('CADASTRAR_AGENTE', 'Cadastrar agente'), ('CADASTRAR_DEPOSITO', 'Cadastrar depósito'), ('DESATIVAR_CADASTRO', 'Desativar cadastro'), ('VER_AUDITORIA', 'Ver auditoria'), ('VER_VALOR_CLIENTE', 'Ver valor cobrado do cliente'), ('VER_CUSTO_AGENTE', 'Ver custo do agente'), ('CONSULTAR_APOIO', 'Consultar CEP e endereço')], max_length=40, verbose_name='Capacidade exigida'),
        ),
    ]
