# Generated by Django 6.0 on 2026-09-24 12:29

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iscas', '0009_alter_registroauditoria_capacidade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='atribuicao',
            name='valor_entrega_cliente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor cobrado do cliente pela entrega'),
        ),
        migrations.AddConstraint(
            model_name='atribuicao',
            constraint=models.CheckConstraint(condition=models.Q(('valor_entrega_cliente__gte', 0), ('valor_entrega_cliente__isnull', True), _connector='OR'), name='iscas_atrib_entrega_nao_negativa'),
        ),
        migrations.AddConstraint(
            model_name='atribuicao',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('origem_tipo', 'RETIRADA_BASE'), _negated=True), ('valor_entrega_cliente__isnull', True), _connector='OR'), name='iscas_atrib_retirada_sem_entrega'),
        ),
    ]
