# Generated by Django 6.0 on 2026-09-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iscas', '0010_valor_entrega_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='atribuicao',
            name='forma_entrega',
            field=models.CharField(choices=[('ENTREGA', 'Entrega ao cliente'), ('RETIRADA', 'Cliente retira')], default='ENTREGA', max_length=20, verbose_name='Forma de entrega'),
        ),
    ]
