# Generated by Django 6.0 on 2026-09-24 14:03

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iscas', '0011_forma_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsolicitacao',
            name='valor_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor unitário'),
        ),
        migrations.AddConstraint(
            model_name='itemsolicitacao',
            constraint=models.CheckConstraint(condition=models.Q(('valor_unitario__gte', 0), ('valor_unitario__isnull', True), _connector='OR'), name='iscas_item_valor_unitario_nao_negativo'),
        ),
    ]
