# Generated by Django 6.0 on 2026-09-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iscas', '0012_valor_unitario_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinatarioNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('nome', models.CharField(blank=True, max_length=120, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Destinatário de notificação',
                'verbose_name_plural': 'Destinatários de notificação',
                'ordering': ['email'],
            },
        ),
        migrations.AlterField(
            model_name='registroauditoria',
            name='capacidade',
            field=models.CharField(blank=True, choices=[('VER_PAINEL', 'Ver painel'), ('VER_MAPA', 'Ver mapa'), ('VER_SOLICITACAO', 'Ver solicitações'), ('CRIAR_SOLICITACAO', 'Criar solicitação'), ('ATENDER_SOLICITACAO', 'Atender solicitação'), ('EXCLUIR_SOLICITACAO', 'Excluir solicitação'), ('VER_ESTOQUE', 'Ver estoque'), ('MOVIMENTAR_ESTOQUE', 'Movimentar estoque'), ('BAIXAR_MANUTENCAO', 'Dar baixa e manutenção'), ('CADASTRAR_CLIENTE', 'Cadastrar cliente'), ('CADASTRAR_MODELO', 'Cadastrar modelo'), ('CADASTRAR_AGENTE', 'Cadastrar agente'), ('CADASTRAR_DEPOSITO', 'Cadastrar depósito'), ('DESATIVAR_CADASTRO', 'Desativar cadastro'), ('VER_AUDITORIA', 'Ver auditoria'), ('CADASTRAR_NOTIFICACAO', 'Cadastrar destinatários de notificação'), ('VER_VALOR_CLIENTE', 'Ver valor cobrado do cliente'), ('VER_CUSTO_AGENTE', 'Ver custo do agente'), ('CONSULTAR_APOIO', 'Consultar CEP e endereço')], max_length=40, verbose_name='Capacidade exigida'),
        ),
    ]
