# Generated by Django 6.0 on 2026-10-05 14:44

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iscas', '0013_destinatario_notificacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='atribuicao',
            name='valor_pedagio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Pedágio pago pelo agente'),
        ),
        migrations.AddConstraint(
            model_name='atribuicao',
            constraint=models.CheckConstraint(condition=models.Q(('valor_pedagio__gte', 0), ('valor_pedagio__isnull', True), _connector='OR'), name='iscas_atrib_pedagio_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='atribuicao',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('origem_tipo', 'RETIRADA_BASE'), _negated=True), ('valor_pedagio__isnull', True), _connector='OR'), name='iscas_atrib_retirada_sem_pedagio'),
        ),
    ]
