# Generated by Django 6.0 on 2026-10-08 12:36

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iscas', '0015_itemsolicitacao_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='valor_assinatura_mensal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Assinatura mensal'),
        ),
        migrations.AddConstraint(
            model_name='solicitacao',
            constraint=models.CheckConstraint(condition=models.Q(('valor_assinatura_mensal__gte', 0), ('valor_assinatura_mensal__isnull', True), _connector='OR'), name='iscas_sol_assinatura_nao_negativa'),
        ),
    ]
