# Generated by Django 6.0 on 2026-10-08 15:19

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iscas', '0016_solicitacao_assinatura_mensal'),
    ]

    operations = [
        migrations.AddField(
            model_name='agente',
            name='valor_retirada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor da retirada'),
        ),
        migrations.CreateModel(
            name='FaixaPrecoAgente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km_ate', models.PositiveIntegerField(verbose_name='Até (km)')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor (R$)')),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faixas_preco', to='iscas.agente', verbose_name='Agente')),
            ],
            options={
                'verbose_name': 'Faixa de preço do agente',
                'verbose_name_plural': 'Faixas de preço do agente',
                'ordering': ['agente', 'km_ate'],
                'constraints': [models.UniqueConstraint(fields=('agente', 'km_ate'), name='iscas_faixa_km_unico'), models.CheckConstraint(condition=models.Q(('km_ate__gt', 0)), name='iscas_faixa_km_positivo'), models.CheckConstraint(condition=models.Q(('valor__gte', 0)), name='iscas_faixa_valor_nao_negativo')],
            },
        ),
    ]
