# Generated by Django 5.1.3 on 2025-11-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cliente", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="equipamento",
            field=models.CharField(
                choices=[
                    ("Isca", "Isca"),
                    ("Rastreador", "Rastreador"),
                    ("Tetis", "Tetis"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
