# Generated by Django 6.0 on 2026-01-18 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamento', '0008_alter_clientes_equipamento'),
        ('produto', '0001_initial'),
        ('registrodemanutencao', '0023_registrodemanutencao_tipo_contrato'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='registro_manutencao_backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_entrada', models.CharField(blank=True, max_length=50, null=True)),
                ('cliente_id_snapshot', models.IntegerField(blank=True, null=True)),
                ('cliente_nome_snapshot', models.CharField(blank=True, max_length=255, null=True)),
                ('produto_id_snapshot', models.IntegerField(blank=True, null=True)),
                ('produto_nome_snapshot', models.CharField(blank=True, max_length=255, null=True)),
                ('motivo', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_customizacao', models.CharField(blank=True, max_length=50, null=True)),
                ('recebimento', models.CharField(blank=True, max_length=50, null=True)),
                ('entregue_por_retirado_por', models.CharField(blank=True, max_length=50, null=True)),
                ('id_equipamentos', models.TextField(blank=True, max_length=1200)),
                ('quantidade', models.IntegerField(blank=True, null=True)),
                ('tipo_contrato', models.CharField(blank=True, max_length=50, null=True)),
                ('customizacaoo', models.CharField(blank=True, max_length=250)),
                ('numero_equipamento', models.TextField(blank=True, max_length=2500)),
                ('observacoes', models.TextField(blank=True, max_length=250)),
                ('tratativa', models.CharField(blank=True, max_length=50, null=True)),
                ('imagem', models.CharField(blank=True, max_length=255, null=True)),
                ('imagem2', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('status_tratativa', models.CharField(blank=True, max_length=50, null=True)),
                ('data_criacao_original', models.DateTimeField(blank=True, null=True)),
                ('data_devolucao', models.DateTimeField(blank=True, null=True)),
                ('backup_criado_em', models.DateTimeField(auto_now_add=True)),
                ('backup_criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('manutencao_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_backups', to='registrodemanutencao.registrodemanutencao')),
                ('nome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acompanhamento.clientes')),
                ('tipo_produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produto.produto')),
            ],
        ),
    ]
