# Generated by Django 6.0 on 2026-01-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrodemanutencao', '0024_registro_manutencao_backup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro_manutencao_backup',
            name='manutencao_original',
        ),
        migrations.AddField(
            model_name='registro_manutencao_backup',
            name='manutencao_original_id',
            field=models.IntegerField(default=0, verbose_name='ID da Manutenção Original'),
            preserve_default=False,
        ),
    ]
