# Generated by Django 6.0 on 2026-01-22 16:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrodemanutencao', '0025_remove_registro_manutencao_backup_manutencao_original_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrodemanutencao',
            name='data_criacao',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
