# Generated by Django 6.0 on 2026-09-30 20:09

import django.db.models.deletion
from django.db import migrations, models


def _backfill_itens(apps, schema_editor):
    """Cada entrada existente vira 1 item com os valores que ela já tinha
    (até aqui a entrada só aceitava um tipo de produto)."""
    Registro = apps.get_model('registrodemanutencao', 'registrodemanutencao')
    ItemEntrada = apps.get_model('registrodemanutencao', 'ItemEntrada')

    ja_migrados = set(ItemEntrada.objects.values_list('registro_id', flat=True))
    campos = ('id', 'tipo_produto_id', 'numero_equipamento', 'customizacaoo',
              'tipo_contrato', 'quantidade')
    itens = [
        ItemEntrada(
            registro_id=rid,
            tipo_produto_id=produto_id,
            numero_equipamento=numeros or '',
            customizacao=customizacao or '',
            tipo_contrato=contrato or '',
            quantidade=quantidade or 0,
        )
        for rid, produto_id, numeros, customizacao, contrato, quantidade
        in Registro.objects.values_list(*campos).iterator()
        if rid not in ja_migrados  # idempotente
    ]
    ItemEntrada.objects.bulk_create(itens, batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
        ('registrodemanutencao', '0026_alter_registrodemanutencao_data_criacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_equipamento', models.TextField(blank=True, default='')),
                ('customizacao', models.CharField(blank=True, choices=[('Sem custumização', 'Sem custumização'), ('Caixa de papelão', 'Caixa de papelão'), ('Caixa de papelão (bateria desacoplada)', 'Caixa de papelão (bateria desacoplada)'), ('Caixa de papelão + DF', 'Caixa de papelão + DF'), ('Termo branco', 'Termo branco'), ('Termo branco + Imã', 'Termo branco + Imã'), ('Termo branco + D.F', 'Termo branco + D.F'), ('Termo branco slim', 'Termo branco slim'), ('Termo branco slim + D.F +EQT', 'Termo branco slim + D.F +EQT'), ('Termo cinza slim + D.F +EQT', 'Termo cinza slim + D.F +EQT'), ('Termo branco (isopor)', 'Termo branco (isopor)'), ('Termo branco - bateria externa', 'Termo branco - bateria externa'), ('Termo marrom + imã', 'Termo marrom + imã'), ('Termo cinza', 'Termo cinza'), ('Termo cinza + imã', 'Termo cinza + imã'), ('Termo preto', 'Termo preto'), ('Termo preto + imã', 'Termo preto + imã'), ('Termo brabco |marrim-slim', 'Termo brabco |marrim-slim'), ('Termo marrom slim +D.F + EQT', 'Termo marrom slim +D.F + EQT'), ('Termo marrom', 'Termo marrom'), ('Caixa blindada', 'Caixa blindada'), ('Tênis/ Sapato', 'Tênis/ Sapato'), ('Projetor', 'Projetor'), ('Caixa de som', 'Caixa de som'), ('Luminaria', 'Luminaria'), ('Alexa', 'Alexa'), ('Video Game', 'Video Game'), ('Secador de cabelo', 'Secador de cabelo'), ('Roteador', 'Roteador'), ('Relogio digital', 'Relogio digital')], default='', max_length=250)),
                ('tipo_contrato', models.CharField(blank=True, choices=[('Descartavel', 'Descartavel'), ('Retornavel', 'Retornavel')], default='', max_length=50)),
                ('quantidade', models.IntegerField(default=0)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='registrodemanutencao.registrodemanutencao')),
                ('tipo_produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_entrada', to='produto.produto')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RunPython(_backfill_itens, migrations.RunPython.noop),
    ]
