# Generated by Django 5.1.2 on 2025-01-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Qualit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data', models.CharField(max_length=50, null=True)),
                ('ID', models.CharField(max_length=50, null=True)),
                ('ID2', models.CharField(max_length=50, null=True)),
                ('ICCID_NOVO', models.CharField(max_length=50)),
                ('CONTRATO', models.CharField(blank=True, choices=[('', ''), ('Descartavel', 'Descartavel'), ('Retornavel', 'Retornavel')], max_length=50, null=True)),
                ('OPERADORA', models.CharField(choices=[('ESEYE', 'ESEYE'), ('1NCE', '1NCE')], max_length=100)),
                ('CLIENTE', models.CharField(max_length=50, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
