# Generated by Django 5.1.3 on 2025-11-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acompanhamento", "0007_clientes_data_treinamento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientes",
            name="equipamento",
            field=models.CharField(
                choices=[
                    ("Isca", "Isca"),
                    ("Rastreador", "Rastreador"),
                    ("Tetis", "Tetis"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
