# Generated by Django 6.0.1 on 2026-03-04 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TarefaMarketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título da Campanha')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição/Briefing')),
                ('status', models.CharField(choices=[('briefing', 'Briefing/Ideia'), ('em_producao', 'Em Produção'), ('aprovacao', 'Aguardando Aprovação'), ('concluido', 'Publicado/Finalizado')], default='briefing', max_length=20, verbose_name='Status')),
                ('responsavel', models.CharField(blank=True, choices=[('felipe nery', 'Felipe Nery'), ('marketing_geral', 'Time Geral')], max_length=50, null=True, verbose_name='Responsável')),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_conclusao', models.DateField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('data_limite', models.DateField(blank=True, null=True, verbose_name='Prazo Final')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], max_length=20, verbose_name='Prioridade')),
                ('cor', models.CharField(choices=[('azul', 'Azul'), ('verde', 'Verde'), ('amarelo', 'Amarelo'), ('laranja', 'Laranja'), ('vermelho', 'Vermelho')], default='azul', max_length=20, verbose_name='Cor')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagens/marketing/')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarefa de Marketing',
                'verbose_name_plural': 'Tarefas de Marketing',
                'ordering': ['-data_criacao', '-id'],
            },
        ),
    ]
