# Generated by Django 6.0.1 on 2026-03-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefamarketing',
            name='responsavel',
            field=models.CharField(blank=True, choices=[('felipe nery', 'Felipe Nery')], max_length=50, null=True, verbose_name='Responsável'),
        ),
    ]
