# Generated by Django 5.0.1 on 2026-03-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_marketing', '0003_tarefamarketing_briefing_aprovado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefamarketing',
            name='status',
            field=models.CharField(choices=[('briefing', 'Briefing/Ideia'), ('em_producao', 'Em Produção'), ('concluido', 'Concluído'), ('publicado', 'Publicado')], default='briefing', max_length=20, verbose_name='Status'),
        ),
    ]
