# Generated by Django 6.0 on 2026-01-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horas',
            name='total_de_horas',
        ),
        migrations.AlterField(
            model_name='horas',
            name='hora_final',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='horas',
            name='hora_inicial',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='horas',
            name='total',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
