# Generated by Django 6.0 on 2026-01-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horas', '0002_remove_horas_total_de_horas_alter_horas_hora_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horas',
            name='total_de_horas',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
