# Generated by Django 5.1.15 on 2026-03-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horas', '0003_horas_total_de_horas'),
    ]

    operations = [
        migrations.AddField(
            model_name='horas',
            name='data_solicitacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Horário da Solicitação'),
        ),
        migrations.AddField(
            model_name='horas',
            name='solicitante',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Solicitante da Hora Extra'),
        ),
        migrations.AlterField(
            model_name='horas',
            name='hora_final',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hora Final'),
        ),
        migrations.AlterField(
            model_name='horas',
            name='hora_inicial',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hora Inicial'),
        ),
    ]
