import os
import sys
import pathlib
import django

# Garantir que o diretório raíz do projeto esteja no sys.path (quando o
# script é executado a partir de scripts/ o sys.path[0] é scripts/, não o
# diretório do projeto). Ajustamos para que o import de 'app.settings' funcione.
project_root = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(project_root))

# Ajuste do módulo de settings do projeto
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'app.settings')
django.setup()

from requisicao.models import Antenista

names = [
"RODRIGO SILVA",
"FELIPPE CAMELO",
"FILIPPE CAMELO",
"JOSÉ ANTONIO",
"CESAR RODRIGO - SPO",
"LUCIO",
"FELIPE MACEDO - SPO",
"RAFAEL ALVES - SPO",
"ANDERSON COSTA / L",
"YURI NETTO",
"HERCULES / FILIPE",
"ALEXANDRE",
"AILTON",
"SATURNINO",
"CLEBSON ARANDU - SPO",
"TENORIO",
"WILSON JOSE",
"WESLEY RODRIGO",
"WESLEY RODRIGO - SPO",
"ANGELO/AGATHA",
"STEVERSON ROGGER",
"IGOR BARBOSA",
"CAIQUE GONÇALVES",
"GIOVAN MENDES",
"RONALDO/SILVA",
"CARDOSO/PAULA",
"BORGES / ALMEIDA - JONAS",
"DINAYDER/CLEITON - JONAS",
"IVAN/LEANDRO - ALEX",
"WILSON JOSE - SPO",
"VINICIUS SUHE",
"AURELIO ANDRADE - RJ",
"THAISY/JOAO PEDRO",
"PAULO VICENTE/LUCIA - JONAS",
"ANDERSON NOGUEIRA",
"THIAGO MATHEUS - SPO",
"SIMEI SANTANA - SPO",
"FLORIANO FERREIRA - SPO",
"AURELIO",
"RAPHAEL/LIMA",
"RIBEIRO/DUTRA",
"HUGO/MOTTA",
"ANDRADE/LEONARDO",
"ANDERSON/MARCIO",
"SILVIO ROMERO",
"ALEX SILVA",
"GABRIEL QUILANTE",
"VITOR ROGERIO",
"MARCIO JUNIOR",
"TADEU",
"LEANDRO FERREIRA - RJ",
"NASCIMENTO/AMERSON",
"IZABEL/SAMPAIO",
"ANDRE/TELES",
"ALLAN/CRISTINA",
"CARLOS MAIA/FELIPE SOUSA",
"FELIPE SOUZA",
"ROBSON RAMIRO",
"WASHINGTON FERNANDES - RJ",
"CARLOS CARVALHO/DIOGO SENA",
"ROGERIO/ISMAEL",
"JANDERSO FERNANDES",
"JOAO MARCOS",
"ADRIANO GONÇALVES",
"COUTINHO/SANTOS",
"NUNES/CRYSOSTOMO",
"ESTEVAO/ULYSSES",
"ALCIDES",
"EZEQUIEL",
"NILDO",
"ALEX",
"ANDERSON",
"ANTONIEQUE",
"OSNI",
"ELTON",
"NEY",
"ANDRÉ",
"RILDO",
"WELLINGTHON",
"GERSON WALACE",
"JUSTINO",
"ANTONIO",
"FRANCISCO",
"OSMAN",
"TONHARA",
"EMERSON",
"MARCELO",
"JEFFERSON",
"GUILHERME",
"MARCIO",
"SAMPAIO",
"DIOGO",
"WESLEY",
"EVERALDO / SAMUEL",
"ERIK",
"LUCAS CARVALHO",
"RODRIGO",
"PITTA",
"JUSTO",
"PAULO HENRIQUE",
"EDUARDO",
"YURI",
"RAFAEL",
"MARLON",
"MALLONE ROCHA DA SILVA",
"Ian Carlos Severino",
"RAY ALBINO -MOGIGUAÇU/SP",
"Barbosa - Nordeste Seguros de FORTALEZA",
"Kelly - DeCaprio Seguros de Belo Horizonte",
"Gilmar Dutra - Natal / RN",
"Redvagner Schroeder Silva / Atibaia - SP",
"Marcio Raimundo da Silva / Pouso Alegre - MG",
"osé Nilton Costa de Souza / Petrolina - PE",
"João Paulo Alexandre da Silva | Maceió - BA",
"Andrei Angelim Pinheiro - MANAUS - AM",
"Valdeci Nunes Neto - Itajaí",
"Oscar Carneiro de Souza Junior",
"Matheus (Praia Grande)",
"André Tsubamoto | Uniforme Seguros",
"Fernandes - Nordeste Seguros",
"Nordeste Seguros - Filial Recife",
"ALEX VIANA CAMPINAS /SP",
"ANDREI MANAUS/AM",
"ERIK- CAMPO DOS GOYTACAZES /RJ",
"SAMUEL - JUIZ DE FORA/MG",
"JOÃO PAULO - MACEIO/AL",
"JOSÉ NILTON - PETROLINA/PE",
"JOSINEY - FEIRA DE SANTANA/BA",
"REDVAGNER -  ATIBAIA/SP",
"RILDO LENNO -BELEM/PA",
"RODRIGO APARECIDO - JUNDIAI/SP",
"CLEITON SILVA  - POÇOES/BA",
]

created = 0
for n in names:
    n = n.strip()
    if not n:
        continue
    obj, created_flag = Antenista.objects.get_or_create(nome=n)
    if created_flag:
        created += 1

print(f"Feito: {created} antenista(s) criados (ou já existentes foram preservados).")
