# Generated by Django 6.0 on 2026-01-21 08:39

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('franquia', '0002_remove_registrodefranquia_km_excedente'),
    ]

    operations = [
        migrations.CreateModel(
            name='registroacompanhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('valor_contrato', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('lucro_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aguardando', 'Aguardando Autorização'), ('faturado', 'Faturado')], default='pendente', max_length=20)),
                ('nf', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nota Fiscal')),
                ('validar_acompanhamento', models.BooleanField(default=False)),
                ('validar_pagamento', models.BooleanField(default=False)),
                ('ocorrencia', models.TextField(blank=True, null=True)),
                ('nome_user', models.CharField(blank=True, max_length=150, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Acompanhamentos',
                'verbose_name_plural': 'Acompanhamentoss',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='registrodeagenteacompanhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Agente')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF')),
                ('pix', models.CharField(blank=True, max_length=100, null=True, verbose_name='Chave Pix')),
                ('banco', models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco')),
                ('agencia', models.CharField(blank=True, max_length=10, null=True, verbose_name='Agência')),
                ('conta', models.CharField(blank=True, max_length=20, null=True, verbose_name='Conta')),
                ('tipo_conta', models.CharField(blank=True, max_length=30, null=True, verbose_name='Tipo de Conta')),
                ('nome_user', models.CharField(blank=True, max_length=150, null=True, verbose_name='Usuário responsável')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Agente de Acompanhamento',
                'verbose_name_plural': 'Agentes de Acompanhamento',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='registrodeclienteacompanhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Cliente')),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True, verbose_name='CNPJ')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('nome_user', models.CharField(blank=True, max_length=150, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='servicosacompanhamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('moto', 'Moto'), ('carro', 'Carro')], max_length=10, verbose_name='Tipo do Serviço')),
                ('agentes', models.PositiveSmallIntegerField(choices=[(1, '1 Agente'), (2, '2 Agentes')], verbose_name='Quantidade de Agentes')),
                ('nomeclatura', models.CharField(max_length=150, verbose_name='Nomenclatura do Serviço')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Serviço de Acompanhamento',
                'verbose_name_plural': 'Serviços de Acompanhamento',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='registroacompanhamentoagente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsavel_agente', models.CharField(blank=True, max_length=100, null=True)),
                ('placa_agente', models.CharField(blank=True, max_length=10, null=True)),
                ('motorista', models.CharField(blank=True, max_length=100, null=True)),
                ('placa_motorista', models.CharField(blank=True, max_length=10, null=True)),
                ('bancario', models.BooleanField(default=False, verbose_name='Pagamento Bancário?')),
                ('pix', models.CharField(blank=True, max_length=100, null=True, verbose_name='Chave Pix')),
                ('banco', models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco')),
                ('agencia', models.CharField(blank=True, max_length=10, null=True, verbose_name='Agência')),
                ('conta', models.CharField(blank=True, max_length=20, null=True, verbose_name='Conta')),
                ('tipo_conta', models.CharField(blank=True, max_length=30, null=True, verbose_name='Tipo de Conta')),
                ('km_inicio', models.IntegerField()),
                ('km_final', models.IntegerField()),
                ('km_total', models.IntegerField(blank=True, null=True)),
                ('km_excedente', models.IntegerField(blank=True, null=True)),
                ('horario_solicitado', models.TimeField()),
                ('horario_inicio', models.TimeField()),
                ('horario_finalizacao', models.TimeField()),
                ('data_solicitada', models.DateField()),
                ('data_inicio', models.DateField()),
                ('data_finalizacao', models.DateField()),
                ('horario_total', models.DurationField(blank=True, null=True)),
                ('horario_excedente', models.DurationField(blank=True, null=True)),
                ('pedagio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('valor_agente', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('acompanhamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agentes', to='acompanhamentos.registroacompanhamento')),
                ('franquia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='franquia.registrodefranquia')),
                ('agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acompanhamentos.registrodeagenteacompanhamento')),
            ],
            options={
                'verbose_name': 'Agente do Acompanhamento',
                'verbose_name_plural': 'Agentes do Acompanhamento',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='registroacompanhamento',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='acompanhamentos.registrodeclienteacompanhamento'),
        ),
        migrations.AddField(
            model_name='registroacompanhamento',
            name='tipo_servico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='acompanhamentos.servicosacompanhamentos'),
        ),
    ]
