# Generated by Django 6.0 on 2026-01-21 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrodeagenteacompanhamento',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Registro de Agentes', 'verbose_name_plural': 'Registros de Agentes'},
        ),
    ]
