# Generated by Django 6.0 on 2026-01-22 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamentos', '0002_alter_registrodeagenteacompanhamento_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroacompanhamentoagente',
            name='cpf_conta',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF (Conta Bancária)'),
        ),
        migrations.AddField(
            model_name='registroacompanhamentoagente',
            name='nome_completo_conta',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome Completo (Conta Bancária)'),
        ),
        migrations.AddField(
            model_name='registroacompanhamentoagente',
            name='tipo_agente',
            field=models.CharField(choices=[('principal', 'Agente Principal'), ('carona', 'Agente no Mesmo Veículo')], default='principal', max_length=20),
        ),
        migrations.AlterField(
            model_name='registroacompanhamento',
            name='tipo_servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acompanhamentos.servicosacompanhamentos'),
        ),
    ]
