# Generated by Django 6.0 on 2026-01-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamentos', '0003_registroacompanhamentoagente_cpf_conta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='registroderesposavelagenteacompanhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Responsável Agente')),
                ('nome_user', models.CharField(blank=True, max_length=150, null=True, verbose_name='Criado por Usuário')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Registro de Responsável Agentes',
                'verbose_name_plural': 'Registros de Responsável Agentes',
                'ordering': ['-criado_em'],
            },
        ),
    ]
