# Generated by Django 6.0 on 2026-01-26 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamentos', '0004_registroderesposavelagenteacompanhamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroacompanhamentoagente',
            name='responsavel_agente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agentes_vinculados', to='acompanhamentos.registroderesposavelagenteacompanhamento', verbose_name='Responsável pelo Agente'),
        ),
    ]
