# Generated by Django 6.0 on 2026-02-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamentos', '0005_alter_registroacompanhamentoagente_responsavel_agente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrodeclienteacompanhamento',
            options={},
        ),
        migrations.AddField(
            model_name='registroacompanhamento',
            name='campo_personalizado_titulo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Título do Campo Personalizado'),
        ),
        migrations.AddField(
            model_name='registroacompanhamento',
            name='campo_personalizado_valor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Valor do Campo Personalizado'),
        ),
        migrations.AddField(
            model_name='registrodeclienteacompanhamento',
            name='franquia_horas',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Franquia de Horas'),
        ),
        migrations.AddField(
            model_name='registrodeclienteacompanhamento',
            name='franquia_km',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Franquia de KM'),
        ),
        migrations.AddField(
            model_name='registrodeclienteacompanhamento',
            name='valor_acionamento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Valor do Acionamento (R$)'),
        ),
        migrations.AddField(
            model_name='registrodeclienteacompanhamento',
            name='valor_horas_excedente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Valor Hora Excedente (R$)'),
        ),
        migrations.AddField(
            model_name='registrodeclienteacompanhamento',
            name='valor_km_excedente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Valor do KM Excedente (R$)'),
        ),
        migrations.AlterField(
            model_name='registrodeclienteacompanhamento',
            name='cnpj',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='registrodeclienteacompanhamento',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
