# Generated by Django 6.0 on 2026-02-04 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamentos', '0006_alter_registrodeclienteacompanhamento_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registroacompanhamento',
            name='botao_panico',
            field=models.BooleanField(default=False, verbose_name='Acionamento via Botão de Pânico'),
        ),
        migrations.AddField(
            model_name='registroacompanhamento',
            name='status_acompanhamento',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('no_local', 'No Local'), ('sem_sinal', 'Sem Sinal'), ('em_andamento', 'Em Andamento'), ('missao_aceita', 'Missão Aceita'), ('concluido', 'Concluído')], default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='registroacompanhamento',
            name='destino',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registroacompanhamentoagente',
            name='data_finalizacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registroacompanhamentoagente',
            name='data_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registroacompanhamentoagente',
            name='data_solicitada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registroacompanhamentoagente',
            name='horario_finalizacao',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registroacompanhamentoagente',
            name='horario_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registroacompanhamentoagente',
            name='horario_solicitado',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registroacompanhamentoagente',
            name='km_final',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registroacompanhamentoagente',
            name='km_inicio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AcompanhamentoLocalizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('origem', models.CharField(choices=[('web', 'Web'), ('pwa', 'PWA'), ('app', 'App')], default='web', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('acompanhamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localizacoes', to='acompanhamentos.registroacompanhamento')),
                ('agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acompanhamentos.registrodeagenteacompanhamento')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['acompanhamento', 'criado_em'], name='acompanhame_acompan_fdbd67_idx')],
            },
        ),
    ]
