# Generated by Django 6.0 on 2026-02-05 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamentos', '0007_registroacompanhamento_botao_panico_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='acompanhamentolocalizacao',
            name='is_panic',
            field=models.BooleanField(default=False, verbose_name='Alerta de Pânico'),
        ),
        migrations.AddField(
            model_name='acompanhamentolocalizacao',
            name='panic_resolved',
            field=models.BooleanField(default=False, verbose_name='Pânico Resolvido'),
        ),
        migrations.AddField(
            model_name='acompanhamentolocalizacao',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Resolvido em'),
        ),
        migrations.AddField(
            model_name='acompanhamentolocalizacao',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panicos_resolvidos', to=settings.AUTH_USER_MODEL, verbose_name='Resolvido por'),
        ),
        migrations.AlterField(
            model_name='acompanhamentolocalizacao',
            name='origem',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Origem do Acompanhamento'),
        ),
    ]
