# Generated by Django 6.0 on 2026-02-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamentos', '0008_acompanhamentolocalizacao_is_panic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroacompanhamento',
            name='latitude_origem',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude do Origem'),
        ),
        migrations.AddField(
            model_name='registroacompanhamento',
            name='longitude_origem',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude do Origem'),
        ),
        migrations.AddField(
            model_name='registroacompanhamento',
            name='raio_cerca',
            field=models.PositiveIntegerField(default=60, verbose_name='Raio da Cerca (metros)'),
        ),
        migrations.AddField(
            model_name='registroacompanhamento',
            name='supabase_mission_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True, verbose_name='ID da missão (Supabase)'),
        ),
        migrations.AlterField(
            model_name='registroacompanhamento',
            name='status_acompanhamento',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('missao_aceita', 'Missão Aceita'), ('odometro_inicio_verificado', 'odômetro Inicial verificado'), ('teste_panico', 'Teste Panico'), ('teste_panico_verificado', 'Teste Panico Verificado'), ('no_local', 'No Local'), ('em_andamento', 'Em Andamento'), ('sem_sinal', 'Sem Sinal'), ('odometro_final_verificado', 'odômetro Final verificado'), ('concluido', 'Concluído')], default='pendente', max_length=40),
        ),
    ]
