# Generated by Django 6.0 on 2026-02-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamentos', '0009_registroacompanhamento_latitude_origem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroacompanhamento',
            name='validado_cliente',
            field=models.BooleanField(default=False),
        ),
    ]
