# Generated by Django 6.0 on 2026-02-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamentos', '0010_registroacompanhamento_validado_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroacompanhamentoagente',
            name='data_placa_final',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora Placa Final'),
        ),
        migrations.AddField(
            model_name='registroacompanhamentoagente',
            name='data_placa_inicio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora Placa Início'),
        ),
        migrations.AddField(
            model_name='registroacompanhamentoagente',
            name='placa_final',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Placa Final'),
        ),
        migrations.AddField(
            model_name='registroacompanhamentoagente',
            name='placa_inicio',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Placa Início'),
        ),
        migrations.AlterField(
            model_name='registroacompanhamento',
            name='status_acompanhamento',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('missao_aceita', 'Missão Aceita'), ('agendada', 'Missão Agendada'), ('em_deslocamento', 'Em Deslocamento'), ('odometro_inicio_verificado', 'odômetro Inicial verificado'), ('teste_panico', 'Teste Panico'), ('teste_panico_verificado', 'Teste Panico Verificado'), ('no_local', 'No Local'), ('em_andamento', 'Em Andamento'), ('sem_sinal', 'Sem Sinal'), ('odometro_final_verificado', 'odômetro Final verificado'), ('concluido', 'Concluído')], default='pendente', max_length=40),
        ),
    ]
