# Generated by Django 6.0 on 2026-02-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamentos', '0011_add_plate_validation_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroacompanhamento',
            name='status_acompanhamento',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('missao_aceita', 'Missão Aceita'), ('agendada', 'Missão Agendada'), ('em_deslocamento', 'Em Deslocamento'), ('no_local', 'No Local'), ('placa_inicio_verificada', 'Placa Inicial Verificada'), ('odometro_inicio_verificado', 'Odômetro Inicial Verificado'), ('teste_panico', 'Teste Pânico'), ('teste_panico_verificado', 'Teste Pânico Verificado'), ('em_andamento', 'Em Andamento'), ('sem_sinal', 'Sem Sinal'), ('odometro_final_verificado', 'Odômetro Final Verificado'), ('placa_final_verificada', 'Placa Final Verificada'), ('concluido', 'Concluído')], default='pendente', max_length=40),
        ),
    ]
