# Generated by Django 6.0 on 2026-02-18 18:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamentos', '0012_update_status_choices_for_plate_validation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_externo', models.IntegerField(help_text='ID do cliente no GSAcionamento', unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('sincronizado_em', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='TipoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_externo', models.IntegerField(help_text='ID do tipo de serviço no GSAcionamento', unique=True)),
                ('codigo', models.CharField(choices=[('MOTO_1', 'Moto | 1 Agente(s) - MOTO MONITORAMENTO ATIVO'), ('CARRO_1', 'Carro | 1 Agente(s) - CARRO MONITORAMENTO ATIVO'), ('CARRO_2', 'Carro | 2 Agente(s) - CARRO MONITORAMENTO ATIVO'), ('CARRO_1_1G', 'Carro | 1 Agente(s) - CARRO MONITORAMENTO ATIVO - 1G'), ('CARRO_2_1S1G', 'Carro | 2 Agente(s) - CARRO MONITORAMENTO ATIVO - 1S/1G'), ('CARRO_2_2G', 'Carro | 2 Agente(s) - CARRO MONITORAMENTO ATIVO - 2G')], max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('valor_acionamento', models.DecimalField(decimal_places=2, default=0, help_text='Valor fixo de acionamento do serviço.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('franquia_km', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('franquia_horas', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('valor_hora', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sincronizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_servico', to='acompanhamentos.cliente')),
            ],
            options={
                'verbose_name': 'Tipo de Serviço',
                'verbose_name_plural': 'Tipos de Serviço',
                'unique_together': {('cliente', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='RequisicaoSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_externo', models.IntegerField(blank=True, help_text='ID da requisição no GSAcionamento', null=True, unique=True)),
                ('campo_personalizado_titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('campo_personalizado_valor', models.CharField(blank=True, max_length=255, null=True)),
                ('origem', models.CharField(max_length=500)),
                ('latitude_origem', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude_origem', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('destino', models.CharField(blank=True, max_length=500, null=True)),
                ('motorista', models.CharField(max_length=255)),
                ('placa', models.CharField(max_length=10)),
                ('data_agendamento', models.DateField()),
                ('horario_agendamento', models.TimeField()),
                ('ocorrencia', models.TextField(blank=True, null=True)),
                ('nome_user', models.CharField(blank=True, max_length=150, null=True)),
                ('sincronizado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='acompanhamentos.cliente')),
                ('tipo_servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisicoes', to='acompanhamentos.tiposervico')),
            ],
            options={
                'verbose_name': 'Requisição de Solicitação',
                'verbose_name_plural': 'Requisições de Solicitações',
                'ordering': ['-criado_em'],
            },
        ),
    ]
