# Generated by Django 6.0 on 2026-02-19 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamentos', '0013_cliente_tiposervico_requisicaosolicitacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicaosolicitacao',
            name='solicitado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registroacompanhamento',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='acompanhamentos.cliente'),
        ),
        migrations.AlterField(
            model_name='registroacompanhamento',
            name='latitude_origem',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True, verbose_name='Latitude do Origem'),
        ),
        migrations.AlterField(
            model_name='registroacompanhamento',
            name='longitude_origem',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True, verbose_name='Longitude do Origem'),
        ),
        migrations.AlterField(
            model_name='registroacompanhamento',
            name='tipo_servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acompanhamentos', to='acompanhamentos.tiposervico'),
        ),
    ]
