# Generated by Django 6.0 on 2026-02-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamentos', '0014_requisicaosolicitacao_solicitado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FranquiaAgente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_externo', models.IntegerField(help_text='ID do tipo de serviço no GSAcionamento', unique=True)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Franquia')),
                ('valor_acionamento', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Valor do Acionamento (R$)')),
                ('franquia_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='Franquia de KM')),
                ('franquia_horas', models.PositiveIntegerField(blank=True, null=True, verbose_name='Franquia de Horas')),
                ('valor_km_excedente', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Valor de KM Excedentes (R$)')),
                ('valor_horas_excedente', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Valor de Horas Excedentes (R$)')),
                ('nome_user', models.CharField(blank=True, max_length=150, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-criado_em'],
                'permissions': [('view_listfranquia', 'Pode visualizar lista de franquias')],
            },
        ),
    ]
