# Generated by Django 6.0 on 2026-02-23 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamentos', '0015_franquiaagente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registrodeclienteacompanhamento',
        ),
        migrations.DeleteModel(
            name='servicosacompanhamentos',
        ),
    ]
