# Generated by Django 6.0 on 2026-02-23 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamentos', '0016_delete_registrodeclienteacompanhamento_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='acompanhamentolocalizacao',
            name='acompanhame_acompan_fdbd67_idx',
        ),
        migrations.AlterField(
            model_name='registroacompanhamentoagente',
            name='franquia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acompanhamentos.franquiaagente'),
        ),
        migrations.DeleteModel(
            name='AcompanhamentoLocalizacao',
        ),
    ]
