# Generated by Django 6.0 on 2026-02-23 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamentos', '0017_remove_acompanhamentolocalizacao_acompanhame_acompan_fdbd67_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Missao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('criado_por', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('encerrada', 'Encerrada')], default='ativa', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missoes', to='acompanhamentos.cliente')),
            ],
            options={
                'verbose_name': 'Missão',
                'verbose_name_plural': 'Missões',
            },
        ),
    ]
