# Generated by Django 6.0 on 2026-02-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamentos', '0018_missao'),
    ]

    operations = [
        migrations.AddField(
            model_name='missao',
            name='id_externo',
            field=models.IntegerField(blank=True, help_text='PK da missão no GS Acionamento', null=True, unique=True),
        ),
    ]
