# Generated by Django 6.0 on 2026-02-23 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamentos', '0019_missao_id_externo'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicaosolicitacao',
            name='missao',
            field=models.ForeignKey(blank=True, help_text='Missão vinculada (sincronizada do GS Acionamento)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisicoes', to='acompanhamentos.missao'),
        ),
    ]
