# Generated by Django 6.0 on 2026-02-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamentos', '0020_requisicaosolicitacao_missao'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicaosolicitacao',
            name='agente',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='requisicaosolicitacao',
            name='placa_agente',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='requisicaosolicitacao',
            name='requisicao_id_externo',
            field=models.IntegerField(blank=True, help_text='PK da Requisicao (acompanhamento) no GS Acionamento', null=True),
        ),
    ]
