# Generated by Django 6.0 on 2026-02-23 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamentos', '0021_requisicaosolicitacao_agente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroacompanhamentoagente',
            name='tipo_servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agentes_acompanhamento', to='acompanhamentos.tiposervico', verbose_name='Tipo de Serviço'),
        ),
    ]
