# Generated by Django 6.0 on 2026-02-23 17:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamentos', '0022_registroacompanhamentoagente_tipo_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroacompanhamento',
            name='comboio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registroacompanhamento',
            name='quantidade_veiculos_comboio',
            field=models.PositiveIntegerField(blank=True, help_text='Quantidade total de veículos no comboio (quando aplicável).', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='requisicaosolicitacao',
            name='comboio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requisicaosolicitacao',
            name='quantidade_veiculos_comboio',
            field=models.PositiveIntegerField(blank=True, help_text='Quantidade total de veículos no comboio (quando aplicável).', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
