# Generated by Django 6.0 on 2026-02-28 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamentos', '0023_registroacompanhamento_comboio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroacompanhamento',
            name='requisicao_solicitacao',
            field=models.ForeignKey(blank=True, help_text='Requisição de solicitação (INT) que originou este acompanhamento. Usado para sincronizar status com o GSAcionamento.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acompanhamentos_int', to='acompanhamentos.requisicaosolicitacao'),
        ),
        migrations.AlterField(
            model_name='registroacompanhamento',
            name='status_acompanhamento',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('missao_aceita', 'Missão Aceita'), ('agendada', 'Missão Agendada'), ('em_deslocamento', 'Em Deslocamento'), ('no_local', 'No Local'), ('placa_inicio_verificada', 'Placa Inicial Verificada'), ('odometro_inicio_verificado', 'Odômetro Inicial Verificado'), ('teste_panico', 'Teste Pânico'), ('teste_panico_verificado', 'Teste Pânico Verificado'), ('em_andamento', 'Em Andamento'), ('disponivel', 'Disponível'), ('sem_sinal', 'Sem Sinal'), ('odometro_final_verificado', 'Odômetro Final Verificado'), ('placa_final_verificada', 'Placa Final Verificada'), ('concluido', 'Concluído')], default='pendente', max_length=40),
        ),
    ]
