# Generated by Django 6.0 on 2026-02-28 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamentos', '0024_registroacompanhamento_requisicao_solicitacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroacompanhamento',
            name='comercial',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cliente Comercial'),
        ),
        migrations.AddField(
            model_name='requisicaosolicitacao',
            name='comercial',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cliente Comercial'),
        ),
    ]
