# Generated by Django 6.0 on 2026-03-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamentos', '0025_registroacompanhamento_comercial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroacompanhamento',
            name='comercial',
        ),
        migrations.RemoveField(
            model_name='requisicaosolicitacao',
            name='comercial',
        ),
        migrations.AddField(
            model_name='cliente',
            name='comercial',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cliente Comercial'),
        ),
    ]
