# Generated by Django 6.0 on 2026-03-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamentos', '0026_remove_registroacompanhamento_comercial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicaosolicitacao',
            name='agente_nome_reuso',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do agente (reuso)'),
        ),
        migrations.AddField(
            model_name='requisicaosolicitacao',
            name='agente_placa_reuso',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Placa do agente (reuso)'),
        ),
        migrations.AddField(
            model_name='requisicaosolicitacao',
            name='is_reuso',
            field=models.BooleanField(default=False, verbose_name='É reuso de agente'),
        ),
    ]
