# Generated by Django 6.0 on 2026-03-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamentos', '0027_requisicaosolicitacao_agente_nome_reuso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroacompanhamento',
            name='tempo_criacao_desde_requisicao',
            field=models.DurationField(blank=True, editable=False, help_text='Diferença entre a criação da RequisiçãoSolicitacao e a criação deste acompanhamento.', null=True, verbose_name='Tempo para criar (desde a requisição)'),
        ),
        migrations.AlterField(
            model_name='tiposervico',
            name='codigo',
            field=models.CharField(choices=[('MOTO_1', 'Moto | 1 Agente(s) - MOTO MONITORAMENTO ATIVO'), ('CARRO_1', 'Carro | 1 Agente(s) - CARRO MONITORAMENTO ATIVO'), ('CARRO_2', 'Carro | 2 Agente(s) - CARRO MONITORAMENTO ATIVO'), ('CARRO_1_1G', 'Carro | 1 Agente(s) - CARRO MONITORAMENTO ATIVO - 1G'), ('CARRO_2_1S1G', 'Carro | 2 Agente(s) - CARRO MONITORAMENTO ATIVO - 1S/1G'), ('CARRO_2_2G', 'Carro | 2 Agente(s) - CARRO MONITORAMENTO ATIVO - 2G'), ('PR_MOTO_1', 'Moto | 1 Agente(s) - PRONTA RESPOSTA'), ('PR_CARRO_1', 'Carro | 1 Agente(s) - PRONTA RESPOSTA'), ('PR_CARRO_2', 'Carro | 2 Agente(s) - PRONTA RESPOSTA')], max_length=20),
        ),
    ]
