# Generated by Django 6.0 on 2026-03-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamentos', '0028_registroacompanhamento_tempo_criacao_desde_requisicao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroacompanhamento',
            name='is_reuso',
            field=models.BooleanField(default=False, help_text='Acompanhamentos de reuso não têm custo para o cliente.', verbose_name='É reuso de agente'),
        ),
        migrations.AlterField(
            model_name='registroacompanhamento',
            name='status_acompanhamento',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('missao_aceita', 'Missão Aceita'), ('agendada', 'Missão Agendada'), ('em_deslocamento', 'Em Deslocamento'), ('no_local', 'No Local'), ('placa_inicio_verificada', 'Placa Inicial Verificada'), ('odometro_inicio_verificado', 'Odômetro Inicial Verificado'), ('teste_panico', 'Teste Pânico'), ('teste_panico_verificado', 'Teste Pânico Verificado'), ('em_andamento', 'Em Andamento'), ('disponivel', 'Disponível'), ('sem_sinal', 'Sem Sinal'), ('odometro_final_verificado', 'Odômetro Final Verificado'), ('placa_final_verificada', 'Placa Final Verificada'), ('concluido', 'Concluído'), ('verificado', 'Verificado')], default='pendente', max_length=40),
        ),
    ]
