# Generated by Django 6.0 on 2026-03-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamentos', '0029_registroacompanhamento_is_reuso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroacompanhamentoagente',
            name='numero_motorista',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
