# Generated by Django 6.0 on 2026-03-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamentos', '0030_registroacompanhamentoagente_numero_motorista'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicaosolicitacao',
            name='numero_motorista',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
