# Generated by Django 6.0 on 2026-03-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamentos', '0031_requisicaosolicitacao_numero_motorista'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tipo_cadastro',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Tipo de atendimento'),
        ),
        migrations.AlterField(
            model_name='tiposervico',
            name='codigo',
            field=models.CharField(choices=[('MOTO_1', 'Moto | 1 Agente(s) - MOTO MONITORAMENTO ATIVO'), ('CARRO_1', 'Carro | 1 Agente(s) - CARRO MONITORAMENTO ATIVO'), ('CARRO_2', 'Carro | 2 Agente(s) - CARRO MONITORAMENTO ATIVO'), ('CARRO_1_1G', 'Carro | 1 Agente(s) - CARRO MONITORAMENTO ATIVO - 1G'), ('CARRO_2_1S1G', 'Carro | 2 Agente(s) - CARRO MONITORAMENTO ATIVO - 1S/1G'), ('CARRO_2_2G', 'Carro | 2 Agente(s) - CARRO MONITORAMENTO ATIVO - 2G'), ('AMBULANCIA', 'Ambulância - Transporte de Paciente'), ('REBOQUE', 'Reboque - Resgate Veicular')], max_length=20),
        ),
    ]
