# Generated by Django 6.0 on 2026-03-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamentos', '0032_cliente_tipo_cadastro_alter_tiposervico_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiposervico',
            name='tipo_cadastro',
            field=models.CharField(blank=True, choices=[('acompanhamento', 'Acompanhamento'), ('pronta_resposta', 'Pronta Resposta')], max_length=20, null=True, verbose_name='Tipo de atendimento'),
        ),
    ]
