# Generated by Django 6.0 on 2026-03-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamentos', '0033_tiposervico_tipo_cadastro'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroacompanhamento',
            name='destino_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registroacompanhamento',
            name='destino_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registroacompanhamento',
            name='latitude_destino',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True, verbose_name='Latitude do Destino'),
        ),
        migrations.AddField(
            model_name='registroacompanhamento',
            name='latitude_destino_2',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True, verbose_name='Latitude do Destino'),
        ),
        migrations.AddField(
            model_name='registroacompanhamento',
            name='latitude_destino_3',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True, verbose_name='Latitude do Destino'),
        ),
        migrations.AddField(
            model_name='registroacompanhamento',
            name='latitude_origem2',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True, verbose_name='Latitude do Origem'),
        ),
        migrations.AddField(
            model_name='registroacompanhamento',
            name='latitude_origem3',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True, verbose_name='Latitude do Origem'),
        ),
        migrations.AddField(
            model_name='registroacompanhamento',
            name='longitude_destino',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True, verbose_name='Longitude do Destino'),
        ),
        migrations.AddField(
            model_name='registroacompanhamento',
            name='longitude_destino_2',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True, verbose_name='Longitude do Destino'),
        ),
        migrations.AddField(
            model_name='registroacompanhamento',
            name='longitude_destino_3',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True, verbose_name='Longitude do Destino'),
        ),
        migrations.AddField(
            model_name='registroacompanhamento',
            name='longitude_origem2',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True, verbose_name='Longitude do Origem'),
        ),
        migrations.AddField(
            model_name='registroacompanhamento',
            name='longitude_origem3',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True, verbose_name='Longitude do Origem'),
        ),
        migrations.AddField(
            model_name='registroacompanhamento',
            name='origem_2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registroacompanhamento',
            name='origem_3',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requisicaosolicitacao',
            name='destino_2',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='requisicaosolicitacao',
            name='destino_3',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='requisicaosolicitacao',
            name='latitude_destino',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='requisicaosolicitacao',
            name='latitude_destino_2',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='requisicaosolicitacao',
            name='latitude_destino_3',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='requisicaosolicitacao',
            name='latitude_origem_2',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='requisicaosolicitacao',
            name='latitude_origem_3',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='requisicaosolicitacao',
            name='longitude_destino',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='requisicaosolicitacao',
            name='longitude_destino_2',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='requisicaosolicitacao',
            name='longitude_destino_3',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='requisicaosolicitacao',
            name='longitude_origem_2',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='requisicaosolicitacao',
            name='longitude_origem_3',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='requisicaosolicitacao',
            name='origem_2',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requisicaosolicitacao',
            name='origem_3',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
