# Generated by Django 6.0 on 2026-03-26 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamentos', '0037_remove_tiposervico_cliente_codigo_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='franquiaagente',
            name='tipo_servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='franquias', to='acompanhamentos.tiposervico', verbose_name='Tipo de Serviço'),
        ),
        migrations.AlterField(
            model_name='tiposervico',
            name='codigo',
            field=models.CharField(choices=[('MOTO_1', 'Moto | 1 Agente(s) - MOTO MONITORAMENTO ATIVO'), ('CARRO_1', 'Carro | 1 Agente(s) - CARRO MONITORAMENTO ATIVO'), ('CARRO_2', 'Carro | 2 Agente(s) - CARRO MONITORAMENTO ATIVO'), ('CARRO_1_1G', 'Carro | 1 Agente(s) - CARRO MONITORAMENTO ATIVO - 1G'), ('CARRO_2_1S1G', 'Carro | 2 Agente(s) - CARRO MONITORAMENTO ATIVO - 1S/1G'), ('CARRO_2_2G', 'Carro | 2 Agente(s) - CARRO MONITORAMENTO ATIVO - 2G'), ('Pronta_Resposta_G', 'Pronta Resposta - 1 Agente(s) - G'), ('Pronta_Resposta_S', 'Pronta Resposta - 1 Agente(s) - S'), ('Antenista', 'Antenista')], max_length=20),
        ),
    ]
