# Generated by Django 6.0 on 2026-03-26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamentos', '0038_franquiaagente_tipo_servico_alter_tiposervico_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='franquiaagente',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='franquias_agente', to='acompanhamentos.cliente', verbose_name='Cliente'),
        ),
    ]
