# Generated by Django 6.0 on 2026-03-31 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamentos', '0039_franquiaagente_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicaosolicitacao',
            name='aceitou_termos_cancelamento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requisicaosolicitacao',
            name='cancelado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requisicaosolicitacao',
            name='justificativa_cancelamento',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='requisicaosolicitacao',
            name='motivos_cancelamento',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='requisicaosolicitacao',
            name='taxa_cancelamento_percentual',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requisicaosolicitacao',
            name='usuario_aceitou_termos_cancelamento',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
