# Generated by Django 6.0 on 2026-03-31 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamentos', '0043_valor_cancelamento_requisicao_e_acompanhamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicaosolicitacao',
            name='cancelamento_aprovado',
            field=models.BooleanField(default=False),
        ),
    ]
