# Generated by Django 6.0 on 2026-04-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamentos', '0044_requisicaosolicitacao_cancelamento_aprovado'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroacompanhamento',
            name='km_estimado_carro',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='registroacompanhamento',
            name='km_estimado_moto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='requisicaosolicitacao',
            name='km_estimado_carro',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='requisicaosolicitacao',
            name='km_estimado_moto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
