# Generated by Django 6.0 on 2026-04-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamentos', '0045_registroacompanhamento_km_estimado_carro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiposervico',
            name='codigo',
            field=models.CharField(choices=[('MOTO_1', 'Moto | 1 Agente(s) - MOTO MONITORAMENTO ATIVO'), ('CARRO_1', 'Carro | 1 Agente(s) - CARRO MONITORAMENTO ATIVO'), ('CARRO_2', 'Carro | 2 Agente(s) - CARRO MONITORAMENTO ATIVO'), ('CARRO_1_1P+', 'Carro | 1 Agente(s) - CARRO MONITORAMENTO ATIVO - 1P+'), ('CARRO_2_1P-1P+', 'Carro | 2 Agente(s) - CARRO MONITORAMENTO ATIVO - 1P-/1P+'), ('CARRO_2_2P+', 'Carro | 2 Agente(s) - CARRO MONITORAMENTO ATIVO - 2P+'), ('Pronta_Resposta_P+', 'Pronta Resposta - 1 Agente(s) - P+'), ('Pronta_Resposta_P-', 'Pronta Resposta - 1 Agente(s) - P-'), ('Antenista', 'Antenista')], max_length=20),
        ),
    ]
