# Generated by Django 6.0 on 2026-05-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acompanhamentos", "0046_alter_tiposervico_codigo"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrodeagenteacompanhamento",
            name="clientes_vinculados",
            field=models.ManyToManyField(
                blank=True,
                related_name="agentes_vinculados",
                to="acompanhamentos.cliente",
                verbose_name="Clientes vinculados",
            ),
        ),
    ]
