# Generated by Django 6.0 on 2026-05-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamentos', '0047_registrodeagenteacompanhamento_clientes_vinculados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroacompanhamentoagente',
            name='data_placa_final',
        ),
        migrations.RemoveField(
            model_name='registroacompanhamentoagente',
            name='data_placa_inicio',
        ),
        migrations.RemoveField(
            model_name='registroacompanhamentoagente',
            name='placa_final',
        ),
        migrations.RemoveField(
            model_name='registroacompanhamentoagente',
            name='placa_inicio',
        ),
        migrations.AlterField(
            model_name='registroacompanhamento',
            name='status_acompanhamento',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('missao_aceita', 'Missão Aceita'), ('agendada', 'Missão Agendada'), ('em_deslocamento', 'Em Deslocamento'), ('no_local', 'No Local'), ('odometro_inicio_verificado', 'Odômetro Inicial Verificado'), ('teste_panico', 'Teste Pânico'), ('teste_panico_verificado', 'Teste Pânico Verificado'), ('em_andamento', 'Em Andamento'), ('disponivel', 'Disponível'), ('sem_sinal', 'Sem Sinal'), ('odometro_final_verificado', 'Odômetro Final Verificado'), ('concluido', 'Concluído'), ('verificado', 'Verificado')], default='pendente', max_length=40),
        ),
    ]
