# Generated by Django 6.0.1 on 2026-01-30 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TarefaTI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('status', models.CharField(choices=[('a_fazer', 'A Fazer'), ('em_progresso', 'Em Progresso'), ('validacao', 'Aguardando Validação'), ('concluido', 'Concluído')], default='a_fazer', max_length=20, verbose_name='Status')),
                ('responsavel', models.CharField(blank=True, choices=[('mayara', 'Mayara'), ('zezinho', 'Zezinho')], max_length=50, null=True, verbose_name='Responsável')),
                ('responsavel_cor', models.CharField(blank=True, default='azul', max_length=20, null=True, verbose_name='Cor do Responsável')),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_conclusao', models.DateField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('data_limite', models.DateField(blank=True, null=True, verbose_name='Prazo')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], max_length=20, verbose_name='Prioridade')),
                ('cor', models.CharField(choices=[('azul', 'Azul'), ('verde', 'Verde'), ('amarelo', 'Amarelo'), ('laranja', 'Laranja'), ('vermelho', 'Vermelho')], default='azul', max_length=20, verbose_name='Cor')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagens/kanban/')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarefa de TI',
                'verbose_name_plural': 'Tarefas de TI',
                'ordering': ['-data_criacao', '-id'],
            },
        ),
    ]
