# Generated by Django 6.0.6 on 2026-06-11 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_TI', '0001_initial'),
        ('kanban_inteligencia', '0019_tarefainteligencia_enviado_kanban_ti_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefati',
            name='ticket_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_ti', to='kanban_inteligencia.tarefainteligencia', verbose_name='Ticket de origem'),
        ),
    ]
