# Generated by Django 6.0.6 on 2026-06-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_TI', '0002_tarefati_ticket_origem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefati',
            name='prioridade',
            field=models.CharField(blank=True, choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], max_length=20, null=True, verbose_name='Prioridade'),
        ),
    ]
