# Generated by Django 6.0 on 2026-03-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nestle', '0002_alter_gridinternacional_status_operacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gridinternacional',
            name='status_operacao',
            field=models.CharField(blank=True, choices=[('Aguardando Liberação RFB', 'Aguardando Liberação RFB'), ('Aguardando Chegada na Base', 'Aguardando Chegada na Base'), ('Aguardando Coleta', 'Aguardando Coleta'), ('Aguardando Embarque Internacional', 'Aguardando Embarque Internacional'), ('Em reversa para o Brasil', 'Em reversa para o Brasil'), ('Retirado, Ag. Envio', 'Retirado, Ag. Envio'), ('Em viagem', 'Em viagem'), ('No destino', 'No destino'), ('Estoque Cliente', 'Estoque Cliente'), ('Danificado', 'Danificado'), ('Extraviado', 'Extraviado'), ('Reversa Finalizada', 'Reversa Finalizada'), ('Equipamento na Base', 'Equipamento na Base'), ('Fora de Operação', 'Fora de Operação')], max_length=255, null=True, verbose_name='Status / Operação'),
        ),
    ]
