# Generated by Django 6.0 on 2026-03-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nestle', '0003_alter_gridinternacional_status_operacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridinternacional',
            name='bateria_chegada_destino',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Bateria na Chegada no Destino (%)'),
        ),
        migrations.AddField(
            model_name='gridinternacional',
            name='bateria_insercao',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Bateria na Inserção (%)'),
        ),
        migrations.AddField(
            model_name='gridinternacional',
            name='media_bateria_viagem',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Média de Bateria da Viagem (%)'),
        ),
    ]
