# Generated by Django 6.0 on 2026-03-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nestle', '0004_gridinternacional_bateria_chegada_destino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridinternacional',
            name='porta_aberta',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Porta Aberta'),
        ),
    ]
