# Generated by Django 6.0 on 2026-04-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nestle', '0007_gridinternacional_anexo_danificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridinternacional',
            name='id2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID 2'),
        ),
    ]
