# Generated by Django 6.0 on 2026-04-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nestle', '0008_gridinternacional_id2'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridinternacional',
            name='quarentena',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Quarentena'),
        ),
    ]
