# Generated by Django 5.2.4 on 2026-01-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_alter_cadastrotipoproduto_nome_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecebimentoChip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solicitacao_compra', models.DateField(verbose_name='Data de Solicitação da Compra')),
                ('data_chegada_golden', models.DateField(verbose_name='Data de Chegada na Golden')),
                ('operadora', models.CharField(max_length=100, verbose_name='Operadora')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('iccid_inicial', models.CharField(max_length=50, verbose_name='ICCID Inicial')),
                ('iccid_final', models.CharField(max_length=50, verbose_name='ICCID Final')),
                ('data_ativacao', models.DateField(verbose_name='Data de Ativação')),
                ('data_envio_configuracao', models.DateField(blank=True, null=True, verbose_name='Data de Envio à Configuração')),
                ('nome_recebedor', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Recebedor')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Recebimento de Chip',
                'verbose_name_plural': 'Recebimentos de Chips',
                'ordering': ['-data_cadastro'],
            },
        ),
    ]
