# Generated by Django 5.2.4 on 2026-01-02 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_recebimentochip'),
    ]

    operations = [
        migrations.AddField(
            model_name='recebimentochip',
            name='quantidade_entregue',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantidade Entregue'),
        ),
        migrations.CreateModel(
            name='EntregaChip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_entregue', models.PositiveIntegerField(verbose_name='Quantidade Entregue')),
                ('responsavel', models.CharField(max_length=200, verbose_name='Responsável pela Entrega')),
                ('data_entrega', models.DateTimeField(auto_now_add=True, verbose_name='Data da Entrega')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('recebimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='compras.recebimentochip', verbose_name='Recebimento')),
            ],
            options={
                'verbose_name': 'Entrega de Chip',
                'verbose_name_plural': 'Entregas de Chips',
                'ordering': ['-data_entrega'],
            },
        ),
    ]
